#!/usr/bin/env bash
# =============================================================================
#  Pingify - point-to-point tunnel manager for Iran <-> Kharej server pairs
#  https://github.com/GreatTeejay/Pingify
#
#  This file is generated by build.sh: it bundles the manager and the whole Go
#  core source, so a single file is everything either server needs.
#  Edit parts/*.sh and core/*.go, then run build.sh - never edit Pingify.sh.
# =============================================================================

PINGIFY_VERSION="3.10.0"
PINGIFY_REPO="GreatTeejay/Pingify"

CFG_DIR="/etc/pingify"
STATE_DIR="/var/lib/pingify"
SRC_DIR="/usr/local/src/pingify"
CORE_BIN="/usr/local/bin/pingify-core"
SELF_BIN="/usr/local/bin/pingify"
UNIT_DIR="/etc/systemd/system"
SYSCTL_FILE="/etc/sysctl.d/99-pingify.conf"
GO_MIN_MINOR=19          # the core needs Go 1.19 or newer
GO_FALLBACK="go1.22.12"  # used only when the version index is unreachable

# ---------------------------------------------------------------------------
# palette
# ---------------------------------------------------------------------------

if [ -t 1 ] && [ "${NO_COLOR:-}" = "" ] && [ "${TERM:-dumb}" != "dumb" ]; then
    C_OFF=$'\033[0m';   C_B=$'\033[1m';    C_DIM=$'\033[2m'
    C_RED=$'\033[31m';  C_GRN=$'\033[32m'; C_YEL=$'\033[33m'
    C_BLU=$'\033[34m';  C_MAG=$'\033[35m'; C_CYN=$'\033[36m'
    C_GRY=$'\033[90m'
else
    C_OFF=""; C_B=""; C_DIM=""; C_RED=""; C_GRN=""; C_YEL=""
    C_BLU=""; C_MAG=""; C_CYN=""; C_GRY=""
fi

# Box drawing degrades to ASCII on a console that is not talking UTF-8, so a
# bare serial session still renders something sane.
PINGIFY_UTF8=0
case "${LC_ALL:-${LC_CTYPE:-${LANG:-}}}" in
    *[Uu][Tt][Ff]*) PINGIFY_UTF8=1 ;;
esac

if [ "$PINGIFY_UTF8" = "1" ]; then
    BX_H='─'; BX_V='│'; BX_TL='╭'; BX_TR='╮'; BX_BL='╰'; BX_BR='╯'
    BX_DOT='·'; BX_ARR='▸'; BX_ON='●'; BX_OFF='○'
    MK_OK='✓'; MK_NO='✗'; MK_WARN='!'
else
    BX_H='-'; BX_V='|'; BX_TL='+'; BX_TR='+'; BX_BL='+'; BX_BR='+'
    BX_DOT='.'; BX_ARR='>'; BX_ON='*'; BX_OFF='o'
    MK_OK='+'; MK_NO='x'; MK_WARN='!'
fi

UI_W=64   # inner width of every panel, so the whole UI lines up

# ---------------------------------------------------------------------------
# drawing primitives
# ---------------------------------------------------------------------------

repeat() { local i n="$2" out=""; for ((i = 0; i < n; i++)); do out="$out$1"; done; printf '%s' "$out"; }

# Visible length, ignoring colour escapes - needed to pad a coloured string.
# Done with parameter expansion rather than sed: the live dashboard redraws
# every two seconds and a subprocess per cell adds up on a small VPS.
vislen() {
    local s="$1" out="" esc=$'\033['
    while [ "${s#*"$esc"}" != "$s" ]; do
        out="$out${s%%"$esc"*}"
        s="${s#*"$esc"}"
        s="${s#*m}"
    done
    out="$out$s"
    printf '%s' "${#out}"
}

pad_to() {
    local s="$1" w="$2" n; n="$(vislen "$s")"
    printf '%s' "$s"
    [ "$n" -lt "$w" ] && repeat ' ' $((w - n))
}

box_top() { printf '  %s%s%s%s%s\n' "$C_GRY" "$BX_TL" "$(repeat "$BX_H" "$UI_W")" "$BX_TR" "$C_OFF"; }
box_bot() { printf '  %s%s%s%s%s\n' "$C_GRY" "$BX_BL" "$(repeat "$BX_H" "$UI_W")" "$BX_BR" "$C_OFF"; }
box_row() { printf '  %s%s%s %s %s%s%s\n' "$C_GRY" "$BX_V" "$C_OFF" "$(pad_to "$1" $((UI_W - 2)))" "$C_GRY" "$BX_V" "$C_OFF"; }

say()  { printf '%s\n' "$*"; }
info() { printf '  %s%s%s %s\n' "$C_CYN" "$BX_ARR" "$C_OFF" "$*"; }
ok()   { printf '  %s%s%s %s\n' "$C_GRN" "$MK_OK" "$C_OFF" "$*"; }
warn() { printf '  %s%s%s %s\n' "$C_YEL" "$MK_WARN" "$C_OFF" "$*"; }
fail() { printf '  %s%s%s %s\n' "$C_RED" "$MK_NO" "$C_OFF" "$*"; }
dim()  { printf '    %s%s%s\n' "$C_DIM" "$*" "$C_OFF"; }
rule() { printf '  %s%s%s\n' "$C_GRY" "$(repeat "$BX_H" $((UI_W + 2)))" "$C_OFF"; }

# A section heading whose rule runs out to the panel width.
head2() {
    local t=" $1 " n; n="$(vislen "$t")"
    printf '\n  %s%s%s%s%s%s%s\n\n' \
        "$C_GRY" "$BX_H$BX_H" "$C_OFF$C_B" "$t" "$C_OFF$C_GRY" \
        "$(repeat "$BX_H" $((UI_W - n)))" "$C_OFF"
}

# item <key> <label> [hint]
#
# The label column grows if a label outruns it, so a long one can never end up
# glued to its hint.
item() {
    local w=28 n
    n="$(vislen "$2")"
    [ "$n" -ge "$w" ] && w=$((n + 2))
    if [ -n "${3:-}" ]; then
        printf '    %s%s%s  %s%s%s%s\n' \
            "$C_CYN$C_B" "$1" "$C_OFF" "$(pad_to "$2" "$w")" "$C_DIM" "$3" "$C_OFF"
    else
        printf '    %s%s%s  %s\n' "$C_CYN$C_B" "$1" "$C_OFF" "$2"
    fi
}

banner() {
    clear 2>/dev/null || true
    printf '\n'
    local l
    if [ "$PINGIFY_UTF8" = "1" ]; then
        for l in \
            '██████╗ ██╗███╗   ██╗ ██████╗ ██╗███████╗██╗   ██╗' \
            '██╔══██╗██║████╗  ██║██╔════╝ ██║██╔════╝╚██╗ ██╔╝' \
            '██████╔╝██║██╔██╗ ██║██║  ███╗██║█████╗   ╚████╔╝ ' \
            '██╔═══╝ ██║██║╚██╗██║██║   ██║██║██╔══╝    ╚██╔╝  ' \
            '██║     ██║██║ ╚████║╚██████╔╝██║██║        ██║   ' \
            '╚═╝     ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝╚═╝        ╚═╝   '
        do
            printf '  %s%s%s\n' "$C_CYN" "$l" "$C_OFF"
        done
    else
        for l in \
            ' ___  _                 _   __       ' \
            '| _ \(_)_ _   __ _   (_) / _|_  _  ' \
            '|  _/| |  \ \ / _` |  | ||  _| || | ' \
            '|_|  |_|_||_|\__, |  |_||_|   \_, | ' \
            '             |___/           |__/  '
        do
            printf '  %s%s%s\n' "$C_CYN" "$l" "$C_OFF"
        done
    fi
    printf '  %s%sby Teejay%s   %sIran %s Kharej tunnel   %s   v%s%s\n\n' \
        "$C_CYN" "$C_DIM" "$C_OFF" "$C_DIM" "$BX_ARR" "$BX_DOT" "$PINGIFY_VERSION" "$C_OFF"
}

pause() { printf '\n'; read -rsp "  ${C_DIM}press enter${C_OFF}" _; printf '\n'; }

# ask VAR "prompt" ["default"]
ask() {
    local __var="$1" __prompt="$2" __def="${3:-}" __in=""
    if [ -n "$__def" ]; then
        read -rp "  ${C_CYN}${BX_ARR}${C_OFF} ${__prompt} ${C_DIM}[${__def}]${C_OFF}${C_B}:${C_OFF} " __in
        [ -z "$__in" ] && __in="$__def"
    else
        read -rp "  ${C_CYN}${BX_ARR}${C_OFF} ${__prompt}${C_B}:${C_OFF} " __in
    fi
    printf -v "$__var" '%s' "$__in"
}

confirm() {
    local reply=""
    read -rp "  ${C_YEL}?${C_OFF} $1 ${C_DIM}[y/N]${C_OFF}${C_B}:${C_OFF} " reply
    case "$reply" in [yY] | [yY][eE][sS]) return 0 ;; *) return 1 ;; esac
}

# A spinner for anything slow, so a download or a build never looks frozen.
spin() {
    local msg="$1"; shift
    if [ ! -t 1 ]; then "$@"; return $?; fi
    "$@" &
    local pid=$! i=0 frames='|/-\'
    while kill -0 "$pid" 2>/dev/null; do
        printf '\r  %s%s%s %s ' "$C_CYN" "${frames:i++%4:1}" "$C_OFF" "$msg"
        sleep 0.1
    done
    wait "$pid"
    local rc=$?
    printf '\r%s\r' "$(repeat ' ' $((${#msg} + 8)))"
    return $rc
}

# ---------------------------------------------------------------------------
# small utilities
# ---------------------------------------------------------------------------

require_root() {
    if [ "$(id -u)" != "0" ]; then
        fail "Pingify has to run as root. Try: sudo pingify"
        exit 1
    fi
}

have() { command -v "$1" >/dev/null 2>&1; }

# These configs are written by this script, one key per line, so a targeted
# sed is enough and Pingify stays free of a jq dependency.
json_str() { sed -n "s/^[[:space:]]*\"$2\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p" "$1" | head -n1; }
json_num() { sed -n "s/^[[:space:]]*\"$2\"[[:space:]]*:[[:space:]]*\([0-9][0-9]*\).*/\1/p" "$1" | head -n1; }

port_free() {
    local p="$1"
    if have ss; then
        ! ss -Hltn "sport = :$p" 2>/dev/null | grep -q . || return 1
    fi
    return 0
}

pick_free_port() {
    local p="${1:-9700}"
    while [ "$p" -lt 65535 ]; do
        if port_free "$p"; then printf '%s' "$p"; return 0; fi
        p=$((p + 1))
    done
    printf '%s' "$1"
}

public_ip() {
    local ip=""
    if have curl; then
        ip=$(curl -4 -fsS --max-time 5 https://api.ipify.org 2>/dev/null)
    fi
    if [ -z "$ip" ] && have ip; then
        ip=$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')
    fi
    printf '%s' "$ip"
}

tunnel_names() {
    [ -d "$CFG_DIR" ] || return 0
    local f
    for f in "$CFG_DIR"/*.json; do
        [ -e "$f" ] || continue
        basename "$f" .json
    done
}

tunnel_count() { tunnel_names | grep -c . ; }

svc_state() {
    if systemctl is-active --quiet "pingify@$1" 2>/dev/null; then printf 'active'
    elif systemctl is-enabled --quiet "pingify@$1" 2>/dev/null; then printf 'stopped'
    else printf 'disabled'; fi
}

# ---------------------------------------------------------------------------
# OS and toolchain
# ---------------------------------------------------------------------------

detect_os() {
    OS_ID="unknown"; OS_VER="0"; OS_PRETTY="unknown"
    if [ -r /etc/os-release ]; then
        # shellcheck disable=SC1091
        . /etc/os-release
        OS_ID="${ID:-unknown}"
        OS_VER="${VERSION_ID:-0}"
        OS_PRETTY="${PRETTY_NAME:-$OS_ID $OS_VER}"
    fi
    ARCH="$(uname -m)"
    case "$ARCH" in
        x86_64 | amd64)  GOARCH="amd64" ;;
        aarch64 | arm64) GOARCH="arm64" ;;
        armv7l | armv6l) GOARCH="armv6l" ;;
        *)               GOARCH="" ;;
    esac
}

apt_install() {
    export DEBIAN_FRONTEND=noninteractive
    if [ "${PINGIFY_APT_UPDATED:-}" != "1" ]; then
        apt-get update -qq >/dev/null 2>&1 || warn "apt-get update reported a problem, continuing"
        PINGIFY_APT_UPDATED=1
    fi
    apt-get install -y -qq "$@" >/dev/null 2>&1
}

ensure_deps() {
    local missing=()
    have curl   || missing+=(curl)
    have tar    || missing+=(tar)
    have ip     || missing+=(iproute2)
    have ss     || missing+=(iproute2)
    have base64 || missing+=(coreutils)
    if [ ${#missing[@]} -gt 0 ]; then
        if have apt-get; then
            spin "installing ${missing[*]}" apt_install "${missing[@]}" \
                || warn "some packages could not be installed"
        else
            warn "please install manually: ${missing[*]}"
        fi
    fi
    mkdir -p "$CFG_DIR" "$STATE_DIR"
    chmod 700 "$CFG_DIR"
}

# Prints the minor version of a Go toolchain, e.g. 22 for go1.22.2, or 0 when
# the binary is unusable or predates the 1.x scheme.
go_version_minor() {
    local v major rest minor
    v="$("$1" version 2>/dev/null | awk '{print $3}')"   # e.g. go1.22.2
    v="${v#go}"
    major="${v%%.*}"; rest="${v#*.}"; minor="${rest%%.*}"
    case "$major.$minor" in
        1.*[!0-9]* | 1.) printf '0'; return ;;
        1.*) printf '%s' "$minor" ;;
        *)   printf '0' ;;
    esac
}

find_go() {
    local cand
    for cand in "$(command -v go 2>/dev/null)" /usr/local/go/bin/go /usr/lib/go/bin/go; do
        [ -n "$cand" ] && [ -x "$cand" ] || continue
        if [ "$(go_version_minor "$cand")" -ge "$GO_MIN_MINOR" ] 2>/dev/null; then
            GO_BIN="$cand"; return 0
        fi
    done
    for cand in /usr/lib/go-*/bin/go; do
        [ -x "$cand" ] || continue
        if [ "$(go_version_minor "$cand")" -ge "$GO_MIN_MINOR" ] 2>/dev/null; then
            GO_BIN="$cand"; return 0
        fi
    done
    return 1
}

install_go_tarball() {
    [ -n "$GOARCH" ] || { fail "unsupported CPU architecture: $ARCH"; return 1; }
    local ver=""
    ver=$(curl -fsS --max-time 8 "https://go.dev/VERSION?m=text" 2>/dev/null | head -n1)
    case "$ver" in go1.*) ;; *) ver="$GO_FALLBACK" ;; esac
    info "downloading $ver for $GOARCH"
    if ! curl -fL --retry 2 --max-time 300 -o /tmp/pingify-go.tgz \
         "https://go.dev/dl/${ver}.linux-${GOARCH}.tar.gz"; then
        fail "could not download the Go toolchain"
        dim "this is only the fallback path - see Update Core for other options"
        return 1
    fi
    rm -rf /usr/local/go
    tar -C /usr/local -xzf /tmp/pingify-go.tgz || return 1
    rm -f /tmp/pingify-go.tgz
    [ -x /usr/local/go/bin/go ] || return 1
    GO_BIN="/usr/local/go/bin/go"
    return 0
}

ensure_go() {
    if find_go; then
        dim "using $("$GO_BIN" version)"
        return 0
    fi
    info "no suitable Go toolchain here (need 1.${GO_MIN_MINOR} or newer)"
    if have apt-get; then
        spin "installing golang-go from the distro" apt_install golang-go
        find_go && { dim "using $("$GO_BIN" version)"; return 0; }
    fi
    install_go_tarball || return 1
    dim "using $("$GO_BIN" version)"
    return 0
}
