#!/usr/bin/env bash
# =============================================================================
#  Pingify - point-to-point tunnel manager for Iran <-> Kharej server pairs
#  https://github.com/GreatTeejay/Pingify
#
#  This file is generated by build.sh: it bundles the manager and the whole Go
#  core source, so a single file is everything either server needs.
#  Edit parts/*.sh and core/*.go, then run build.sh - never edit Pingify.sh.
# =============================================================================

PINGIFY_VERSION="1.0.5"
PINGIFY_REPO="GreatTeejay/Pingify"

# Everything Pingify owns lives in one directory, so it is obvious what is
# installed and trivial to back up or delete.
BASE_DIR="/root/Pingify"
CFG_DIR="$BASE_DIR"
STATE_DIR="$BASE_DIR/.state"
SRC_DIR="$BASE_DIR/.build"
CORE_BIN="$BASE_DIR/pingify-core"
SELF_BIN="/usr/local/bin/pingify"   # has to be on PATH for the "pingify" command
UNIT_DIR="/etc/systemd/system"
SYSCTL_FILE="/etc/sysctl.d/99-pingify.conf"
# AmneziaWG reads its interface config from a file, and awg-quick names the
# interface after that file, so ours live under Pingify's own directory.
AWG_DIR="$BASE_DIR/awg"
GO_MIN_MINOR=19          # the core needs Go 1.19 or newer
GO_FALLBACK="go1.22.12"  # used only when the version index is unreachable

# ---------------------------------------------------------------------------
# palette
# ---------------------------------------------------------------------------

if [ -t 1 ] && [ "${NO_COLOR:-}" = "" ] && [ "${TERM:-dumb}" != "dumb" ]; then
    C_OFF=$'\033[0m';   C_B=$'\033[1m';    C_DIM=$'\033[2m'
    C_RED=$'\033[31m';  C_GRN=$'\033[32m'; C_YEL=$'\033[33m'
    C_BLU=$'\033[34m';  C_MAG=$'\033[35m'; C_CYN=$'\033[36m'
    C_GRY=$'\033[90m'
else
    C_OFF=""; C_B=""; C_DIM=""; C_RED=""; C_GRN=""; C_YEL=""
    C_BLU=""; C_MAG=""; C_CYN=""; C_GRY=""
fi

# Box drawing degrades to ASCII on a console that is not talking UTF-8, so a
# bare serial session still renders something sane.
PINGIFY_UTF8=0
case "${LC_ALL:-${LC_CTYPE:-${LANG:-}}}" in
    *[Uu][Tt][Ff]*) PINGIFY_UTF8=1 ;;
esac

if [ "$PINGIFY_UTF8" = "1" ]; then
    BX_H='─'; BX_V='│'; BX_TL='╭'; BX_TR='╮'; BX_BL='╰'; BX_BR='╯'
    BX_DOT='·'; BX_ARR='▸'; BX_ON='●'; BX_OFF='○'
    MK_OK='✓'; MK_NO='✗'; MK_WARN='!'
else
    BX_H='-'; BX_V='|'; BX_TL='+'; BX_TR='+'; BX_BL='+'; BX_BR='+'
    BX_DOT='.'; BX_ARR='>'; BX_ON='*'; BX_OFF='o'
    MK_OK='+'; MK_NO='x'; MK_WARN='!'
fi

UI_W=64   # inner width of every panel, so the whole UI lines up

# ---------------------------------------------------------------------------
# drawing primitives
# ---------------------------------------------------------------------------

repeat() { local i n="$2" out=""; for ((i = 0; i < n; i++)); do out="$out$1"; done; printf '%s' "$out"; }

# Visible length, ignoring colour escapes - needed to pad a coloured string.
# Done with parameter expansion rather than sed: the live dashboard redraws
# every two seconds and a subprocess per cell adds up on a small VPS.
vislen() {
    local s="$1" out="" esc=$'\033['
    while [ "${s#*"$esc"}" != "$s" ]; do
        out="$out${s%%"$esc"*}"
        s="${s#*"$esc"}"
        s="${s#*m}"
    done
    out="$out$s"
    printf '%s' "${#out}"
}

pad_to() {
    local s="$1" w="$2" n; n="$(vislen "$s")"
    printf '%s' "$s"
    [ "$n" -lt "$w" ] && repeat ' ' $((w - n))
}

# ---------------------------------------------------------------------------
# round trip time
#
# The number on its own means nothing to most people looking at it. What they
# want to know is whether it is normal for this path, so the bands are drawn
# where an Iran <-> abroad tunnel changes character rather than at round
# numbers:
#
#   under 100 ms   a European or nearby datacentre behaving itself
#   100 - 200 ms   usable, but interactive traffic feels it
#   over 200 ms    either a very long way round, or the path is in trouble
#
# A tunnel that is down has no round trip at all, and that is dim, not red -
# red here should mean "this path is slow", not "there is no path".
# ---------------------------------------------------------------------------
# An address is the thing on these screens people copy, compare and mistype,
# so it gets a colour of its own rather than sitting in the same weight as the
# words around it.
addr_tint() { printf '%s%s%s' "$C_CYN" "$1" "$C_OFF"; }

rtt_colour() {
    local ms="${1%ms}"; ms="${ms%%.*}"
    case "$ms" in
        '' | *[!0-9]*) printf '%s' "$C_DIM"; return ;;
    esac
    if   [ "$ms" -lt 100 ]; then printf '%s' "$C_GRN"
    elif [ "$ms" -lt 200 ]; then printf '%s' "$C_YEL"
    else                         printf '%s' "$C_RED"
    fi
}

# rtt_tint prints the value already wrapped in its colour.
rtt_tint() { printf '%s%s%s' "$(rtt_colour "$1")" "$1" "$C_OFF"; }

# true when the path is slow enough to be worth a word of explanation
rtt_slow() {
    local ms="${1%ms}"; ms="${ms%%.*}"
    case "$ms" in '' | *[!0-9]*) return 1 ;; esac
    [ "$ms" -ge 200 ]
}

# A panel carries its title in the top border, so a screen full of them reads
# as a list of labelled blocks rather than a wall of rules.
panel() {
    local t="${1:-}" n
    if [ -z "$t" ]; then
        printf '  %s%s%s%s%s\n' "$C_GRY" "$BX_TL" "$(repeat "$BX_H" "$UI_W")" "$BX_TR" "$C_OFF"
        return
    fi
    # corner + one rule + " title " ; the rest of the line is rule + corner
    n=$(( ${#t} + 3 ))
    printf '  %s%s%s %s%s%s %s%s%s\n' \
        "$C_GRY" "$BX_TL$BX_H" "$C_OFF" "$C_CYN$C_B" "$t" "$C_OFF" \
        "$C_GRY" "$(repeat "$BX_H" $((UI_W - n)))$BX_TR" "$C_OFF"
}

panel_end() { printf '  %s%s%s%s%s\n' "$C_GRY" "$BX_BL" "$(repeat "$BX_H" "$UI_W")" "$BX_BR" "$C_OFF"; }

row() {
    printf '  %s%s%s %s %s%s%s\n' \
        "$C_GRY" "$BX_V" "$C_OFF" "$(pad_to "$1" $((UI_W - 2)))" "$C_GRY" "$BX_V" "$C_OFF"
}

# field <label> <value> [label2] [value2] - two aligned columns in one row.
field() {
    local s
    s="$(pad_to "${C_DIM}$1${C_OFF}" 13)${C_B}$2${C_OFF}"
    if [ -n "${3:-}" ]; then
        s="$(pad_to "$s" 32)$(pad_to "${C_DIM}$3${C_OFF}" 12)${C_B}$4${C_OFF}"
    fi
    row "$s"
}

# kept so older call sites keep working
box_top() { panel; }
box_bot() { panel_end; }
box_row() { row "$1"; }

say()  { printf '%s\n' "$*"; }
info() { printf '  %s%s%s %s\n' "$C_CYN" "$BX_ARR" "$C_OFF" "$*"; }
ok()   { printf '  %s%s%s %s\n' "$C_GRN" "$MK_OK" "$C_OFF" "$*"; }
warn() { printf '  %s%s%s %s\n' "$C_YEL" "$MK_WARN" "$C_OFF" "$*"; }
fail() { printf '  %s%s%s %s\n' "$C_RED" "$MK_NO" "$C_OFF" "$*"; }
dim()  { printf '    %s%s%s\n' "$C_DIM" "$*" "$C_OFF"; }
rule() { printf '  %s%s%s\n' "$C_GRY" "$(repeat "$BX_H" $((UI_W + 2)))" "$C_OFF"; }

# A section heading whose rule runs out to the panel width.
head2() {
    local t=" $1 " n; n="$(vislen "$t")"
    printf '\n  %s%s%s%s%s%s%s\n\n' \
        "$C_GRY" "$BX_H$BX_H" "$C_OFF$C_CYN$C_B" "$t" "$C_OFF$C_GRY" \
        "$(repeat "$BX_H" $((UI_W - n)))" "$C_OFF"
}

# A label above a run of related menu entries.
group() { printf '\n  %s%s%s\n' "$C_DIM$C_B" "$1" "$C_OFF"; }

# item <key> <label> [hint]
#
# The label column grows if a label outruns it, so a long one can never end up
# glued to its hint.
item() {
    local w=24 n
    n="$(vislen "$2")"
    [ "$n" -ge "$w" ] && w=$((n + 2))
    if [ -n "${3:-}" ]; then
        printf '    %s%s%s %s%s%s %s%s%s\n' \
            "$C_CYN$C_B" "$1" "$C_OFF" "$C_GRY" "$BX_ARR" "$C_OFF" \
            "$(pad_to "$2" "$w")" "$C_DIM" "$3$C_OFF"
    else
        printf '    %s%s%s %s%s%s %s\n' \
            "$C_CYN$C_B" "$1" "$C_OFF" "$C_GRY" "$BX_ARR" "$C_OFF" "$2"
    fi
}

# ---------------------------------------------------------------------------
# the wizard
#
# The steps run down one page. Nothing is cleared between them, so the answers
# already given stay on screen above the question being asked - which is what
# you want when you are copying the same numbers onto a second server.
# ---------------------------------------------------------------------------

WIZ_STEP=0

# A wizard is a run of questions that only means something finished. Half
# of one is not a tunnel, so there has to be a way out that is not ctrl-c -
# and it has to work at every question, not only the first.
#
# ask sets WIZ_QUIT when the answer is q, and every question after that
# returns without asking, so the wizard unwinds instead of finishing.
wiz_reset() { WIZ_STEP=0; WIZ_ACTIVE=1; WIZ_QUIT=0; }
wiz_end()   { WIZ_ACTIVE=0; WIZ_QUIT=0; }
wiz_quit()  { [ "${WIZ_QUIT:-0}" = "1" ]; }

# Kept so the wizard can note a decision without the page having to redraw.
wiz_add() { :; }

# wiz <title> [subtitle] - open a step.
wiz() {
    WIZ_STEP=$((WIZ_STEP + 1))
    local t="$WIZ_STEP $BX_DOT $1 " n; n="$(vislen " $t")"
    printf '\n  %s%s%s%s%s%s%s\n\n' \
        "$C_GRY" "$BX_H$BX_H " "$C_OFF$C_CYN$C_B" "$t" "$C_OFF$C_GRY" \
        "$(repeat "$BX_H" $((UI_W - n)))" "$C_OFF"
    [ -n "${2:-}" ] && { dim "$2"; say ""; }
    return 0
}

# choice <key> <name> <hint> - one option, name and reason on the same line.
#
# CHOICE_DEF marks the one enter picks, on the line itself. Having to read the
# prompt underneath to work out which number that is, is a step nobody should
# have to take.
CHOICE_DEF=""
choice() {
    local mark="   " hint="${3:-}"
    if [ "$1" = "$CHOICE_DEF" ]; then
        mark="${C_GRN}${BX_ARR}${C_OFF}  "
        hint="${hint}${hint:+  }${C_GRN}(default)${C_OFF}"
    fi
    printf '  %s%s%s%s  %s  %s%s%s\n' \
        "$mark" "$C_CYN$C_B" "$1" "$C_OFF" \
        "$(pad_to "${C_B}$2${C_OFF}" 14)" \
        "$C_DIM" "$hint" "$C_OFF"
}

# state <on|off> - a coloured on/off badge for toggles.
state_badge() {
    if [ "$1" = "on" ]; then
        printf '%s%s on%s' "$C_GRN" "$BX_ON" "$C_OFF"
    else
        printf '%s%s off%s' "$C_GRY" "$BX_OFF" "$C_OFF"
    fi
}

banner() {
    clear 2>/dev/null || true
    printf '\n'
    local l w pad
    if [ "$PINGIFY_UTF8" = "1" ]; then
        set -- \
            '██████╗ ██╗███╗   ██╗ ██████╗ ██╗███████╗██╗   ██╗' \
            '██╔══██╗██║████╗  ██║██╔════╝ ██║██╔════╝╚██╗ ██╔╝' \
            '██████╔╝██║██╔██╗ ██║██║  ███╗██║█████╗   ╚████╔╝ ' \
            '██╔═══╝ ██║██║╚██╗██║██║   ██║██║██╔══╝    ╚██╔╝  ' \
            '██║     ██║██║ ╚████║╚██████╔╝██║██║        ██║   ' \
            '╚═╝     ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝╚═╝        ╚═╝   '
    else
        set -- \
            ' ___  _                 _   __     ' \
            '| _ \(_)_ _  __ _ (_) / _|_  _     ' \
            '|  _/| | | \| | (_| | | ||  _| || |' \
            '|_|  |_|_||_|\__, | |_||_|   \_, |ذ' \
            '             |___/          |__/   '
    fi

    # The name sits in its own frame, centred, so the page opens with one
    # object rather than six lines floating above a rule.
    w=0
    for l in "$@"; do
        [ "$(vislen "$l")" -gt "$w" ] && w="$(vislen "$l")"
    done
    local inner=$((UI_W))
    pad=$(( (inner - w) / 2 ))
    [ "$pad" -lt 0 ] && pad=0

    printf '  %s%s%s%s%s\n' "$C_CYN$C_DIM" "$BX_TL" "$(repeat "$BX_H" "$inner")" "$BX_TR" "$C_OFF"
    for l in "$@"; do
        printf '  %s%s%s%s%s%s%s%s\n' \
            "$C_CYN$C_DIM" "$BX_V" "$C_OFF" \
            "$(repeat ' ' "$pad")" "$C_CYN$C_B$l$C_OFF" \
            "$(repeat ' ' $((inner - pad - $(vislen "$l"))))" \
            "$C_CYN$C_DIM$BX_V" "$C_OFF"
    done

    # and the one line that says what it is, centred under it
    local sub="by Teejay   ${BX_DOT}   Iran ${BX_ARR} Kharej tunnel"
    pad=$(( (inner - ${#sub}) / 2 ))
    [ "$pad" -lt 0 ] && pad=0
    printf '  %s%s%s%s%s%s%s%s\n' \
        "$C_CYN$C_DIM" "$BX_V" "$C_OFF" \
        "$(repeat ' ' "$pad")" "$C_DIM$sub$C_OFF" \
        "$(repeat ' ' $((inner - pad - ${#sub})))" \
        "$C_CYN$C_DIM$BX_V" "$C_OFF"
    printf '  %s%s%s%s%s\n\n' "$C_CYN$C_DIM" "$BX_BL" "$(repeat "$BX_H" "$inner")" "$BX_BR" "$C_OFF"
}

pause() { printf '\n'; read -rsp "  ${C_DIM}press enter${C_OFF}" _; printf '\n'; }

# ask VAR "prompt" ["default"]
ask() {
    local __var="$1" __prompt="$2" __def="${3:-}" __in=""
    # Already leaving: do not ask, and do not block a validation loop that
    # would otherwise sit here forever waiting for an answer nobody is
    # going to give.
    [ "${WIZ_QUIT:-0}" = "1" ] && return 1
    local __rc=0
    if [ -n "$__def" ]; then
        read -rp "  ${C_CYN}${BX_ARR}${C_OFF} ${__prompt} ${C_DIM}[${__def}]${C_OFF}${C_B}:${C_OFF} " __in || __rc=1
        [ -z "$__in" ] && __in="$__def"
    else
        read -rp "  ${C_CYN}${BX_ARR}${C_OFF} ${__prompt}${C_B}:${C_OFF} " __in || __rc=1
    fi
    # Standard input has ended. No answer is coming, and pick would sit here
    # rejecting the empty one and asking again, forever - which is what a
    # script piped into this used to do instead of stopping.
    if [ "$__rc" = "1" ] && [ -z "$__in" ]; then
        [ "${WIZ_ACTIVE:-0}" = "1" ] && WIZ_QUIT=1
        return 1
    fi
    if [ "${WIZ_ACTIVE:-0}" = "1" ]; then
        case "$__in" in
            q | Q | quit) WIZ_QUIT=1; return 1 ;;
        esac
    fi
    printf -v "$__var" '%s' "$__in"
}

# pick <var> <prompt> <valid>... - insist on one of the listed answers.
#
# Some questions have no sensible default. Which server this is, what protocol
# to speak, who forwards - an empty enter that quietly means "the first one" is
# how somebody ends up with a tunnel they did not choose and cannot explain.
# The locals here are named apart from ask's on purpose. bash scopes locals
# dynamically, so a caller that asks ask to write into a variable ask also
# declares local gets ask's copy, and the caller's stays empty - which is a
# loop that rejects every answer, forever.
pick() {
    local _pk_var="$1" _pk_prompt="$2"; shift 2
    local _pk_in="" _pk_opt
    while :; do
        ask _pk_in "$_pk_prompt" || return 1
        if [ -z "$_pk_in" ]; then
            fail "this one has no default - choose $(printf '%s or ' "$@" | sed 's/ or $//')"
            continue
        fi
        for _pk_opt in "$@"; do
            if [ "$_pk_in" = "$_pk_opt" ]; then
                printf -v "$_pk_var" '%s' "$_pk_in"
                return 0
            fi
        done
        fail "not one of the options - choose $(printf '%s or ' "$@" | sed 's/ or $//')"
    done
}

# confirm_yes is confirm with the answer already leaning the right way: by the
# time it is asked, everything has been reviewed and the expected reply is yes.
confirm_yes() {
    local reply=""
    [ "${WIZ_QUIT:-0}" = "1" ] && return 1
    read -rp "  ${C_YEL}?${C_OFF} $1 ${C_DIM}[Y/n]${C_OFF}${C_B}:${C_OFF} " reply
    if [ "${WIZ_ACTIVE:-0}" = "1" ]; then
        case "$reply" in q | Q | quit) WIZ_QUIT=1; return 1 ;; esac
    fi
    case "$reply" in [nN] | [nN][oO]) return 1 ;; *) return 0 ;; esac
}

confirm() {
    local reply=""
    read -rp "  ${C_YEL}?${C_OFF} $1 ${C_DIM}[y/N]${C_OFF}${C_B}:${C_OFF} " reply
    case "$reply" in [yY] | [yY][eE][sS]) return 0 ;; *) return 1 ;; esac
}

# A spinner for anything slow, so a download or a build never looks frozen.
spin() {
    local msg="$1"; shift
    if [ ! -t 1 ]; then "$@"; return $?; fi
    "$@" &
    local pid=$! i=0 frames='|/-\'
    while kill -0 "$pid" 2>/dev/null; do
        printf '\r  %s%s%s %s ' "$C_CYN" "${frames:i++%4:1}" "$C_OFF" "$msg"
        sleep 0.1
    done
    wait "$pid"
    local rc=$?
    printf '\r%s\r' "$(repeat ' ' $((${#msg} + 8)))"
    return $rc
}

# ---------------------------------------------------------------------------
# small utilities
# ---------------------------------------------------------------------------

require_root() {
    if [ "$(id -u)" != "0" ]; then
        fail "Pingify has to run as root. Try: sudo pingify"
        exit 1
    fi
}

have() { command -v "$1" >/dev/null 2>&1; }

# fetch <url> <dest> [timeout] - download one file with whatever this machine
# has. The install line is written with wget, so wget is the tool most likely
# to be present and curl the one most likely to be missing; assuming curl left
# servers quietly running an old script while the core updated around them.
fetch() {
    local url="$1" dest="$2" t="${3:-120}"
    if have curl; then
        curl -fsSL --retry 2 --max-time "$t" -o "$dest" "$url" && return 0
    fi
    if have wget; then
        wget -q --tries=2 --timeout="$t" -O "$dest" "$url" && return 0
    fi
    return 1
}

# Config files are TOML written by this script, one key per line, so a
# targeted sed reads them back and Pingify needs no parser of its own.
CFG_EXT="toml"

cfg_file() { printf '%s/%s.%s' "$CFG_DIR" "$1" "$CFG_EXT"; }

toml_arr() { [ -f "$1" ] || return 0; sed -n "s/^[[:space:]]*$2[[:space:]]*=[[:space:]]*\[\(.*\)\].*/\1/p" "$1" | head -n1; }

# toml_get <file> <section> <key> - reads a value out of one [section].
# Values keep their quotes off and numeric underscores stripped.
# The public name of a security token: eight characters derived from it, safe
# to read aloud. Both servers print the same one when the token matches, which
# is the only way to tell a wrong token apart from a broken network.
token_print() {
    local t
    t="$(printf '%s' "${1:-}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    [ -n "$t" ] && printf '%s' "$t" | sha256sum | cut -c1-8 || printf 'none'
}

toml_get() {
    [ -f "$1" ] || return 0
    awk -v want="$2" -v key="$3" '
        function quoted(s, out, i, c, n) {
            # The manager writes basic TOML strings and escapes backslash and
            # quote. Decode exactly those two here; a # inside the quotes is
            # data, not a comment (security tokens commonly contain one).
            for (i = 2; i <= length(s); i++) {
                c = substr(s, i, 1)
                if (c == "\\") {
                    n = substr(s, i + 1, 1)
                    if (n == "\\" || n == "\"") { out = out n; i++; continue }
                    out = out c
                    continue
                }
                if (c == "\"") return out
                out = out c
            }
            return out
        }
        /^[[:space:]]*\[/ { s = $0; gsub(/[][[:space:]]/, "", s); cur = s; next }
        cur == want {
            line = $0
            if (match(line, "^[[:space:]]*" key "[[:space:]]*=")) {
                v = substr(line, RSTART + RLENGTH)
                gsub(/^[[:space:]]+|[[:space:]]+$/, "", v)
                if (v ~ /^"/) v = quoted(v)
                else {
                    sub(/[[:space:]]*#.*$/, "", v)
                    gsub(/[[:space:]]+$/, "", v)
                    if (v ~ /^[0-9_]+$/) gsub(/_/, "", v)
                }
                print v
                exit
            }
        }' "$1"
}


# Only used to convert a config left behind by 3.2 or earlier.
json_str() { [ -f "$1" ] || return 0; sed -n "s/^[[:space:]]*\"$2\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p" "$1" | head -n1; }
json_num() { [ -f "$1" ] || return 0; sed -n "s/^[[:space:]]*\"$2\"[[:space:]]*:[[:space:]]*\([0-9][0-9]*\).*/\1/p" "$1" | head -n1; }

# port_free PORT [PROTO] - nothing is listening there. PROTO is tcp unless
# said otherwise; a UDP socket and a TCP socket on the same number are two
# different things and neither blocks the other.
port_free() {
    local p="$1" proto="${2:-tcp}"
    if have ss; then
        case "$proto" in
            udp) ! ss -Hlun "sport = :$p" 2>/dev/null | grep -q . || return 1 ;;
            *)   ! ss -Hltn "sport = :$p" 2>/dev/null | grep -q . || return 1 ;;
        esac
    fi
    return 0
}

pick_free_port() {
    local p="${1:-9700}"
    while [ "$p" -lt 65535 ]; do
        if port_free "$p"; then printf '%s' "$p"; return 0; fi
        p=$((p + 1))
    done
    printf '%s' "$1"
}

# The status endpoint has to be unique per tunnel. Asking the kernel whether a
# port is free only answers for the tunnels that happen to be running right
# now, so a second tunnel built while the first one was stopped was handed the
# same port - and then the two of them fought over it at the next boot, with
# the loser reporting no carriers to a health check that could see nothing
# wrong with it.
pick_status_port() {
    local want="${1:-9700}" p="${1:-9700}" taken="" f
    for f in "$CFG_DIR"/*.toml "$CFG_DIR"/*.json; do
        [ -f "$f" ] || continue
        taken="$taken $(toml_get "$f" status addr)"
    done
    while [ "$p" -lt 65535 ]; do
        case " $taken " in
            *":$p "*) p=$((p + 1)); continue ;;
        esac
        if port_free "$p"; then printf '%s' "$p"; return 0; fi
        p=$((p + 1))
    done
    printf '%s' "$want"
}

public_ip() {
    local ip=""
    if have curl; then
        ip=$(curl -4 -fsS --max-time 5 https://api.ipify.org 2>/dev/null)
    fi
    if [ -z "$ip" ] && have ip; then
        ip=$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')
    fi
    printf '%s' "$ip"
}

tunnel_names() {
    [ -d "$CFG_DIR" ] || return 0
    local f
    for f in "$CFG_DIR"/*."$CFG_EXT"; do
        [ -e "$f" ] || continue
        basename "$f" ".$CFG_EXT"
    done
}

# Where this server sits, for the panel on the front page. Best effort: an
# Iranian box may not reach the lookup service, in which case the local route
# still gives us the address.
server_info() {
    [ -n "${SRV_IP:-}" ] && return 0
    SRV_IP=""; SRV_LOC=""; SRV_ORG=""
    if have curl; then
        local j
        j="$(curl -fsS --max-time 6 'http://ip-api.com/json/?fields=query,country,isp' 2>/dev/null)"
        if [ -n "$j" ]; then
            SRV_IP="$(printf  '%s' "$j" | sed -n 's/.*"query":"\([^"]*\)".*/\1/p')"
            SRV_LOC="$(printf '%s' "$j" | sed -n 's/.*"country":"\([^"]*\)".*/\1/p')"
            SRV_ORG="$(printf '%s' "$j" | sed -n 's/.*"isp":"\([^"]*\)".*/\1/p')"
        fi
    fi
    [ -n "$SRV_IP" ] || SRV_IP="$(public_ip)"
    [ -n "$SRV_IP" ] || SRV_IP="unknown"
    [ -n "$SRV_LOC" ] || SRV_LOC="unknown"
    [ -n "$SRV_ORG" ] || SRV_ORG="unknown"
}

tunnel_count() { tunnel_names | grep -c . ; }

svc_state() {
    if systemctl is-active --quiet "pingify@$1" 2>/dev/null; then printf 'active'
    elif systemctl is-enabled --quiet "pingify@$1" 2>/dev/null; then printf 'stopped'
    else printf 'disabled'; fi
}

# ---------------------------------------------------------------------------
# OS and toolchain
# ---------------------------------------------------------------------------

detect_os() {
    OS_ID="unknown"; OS_VER="0"; OS_PRETTY="unknown"
    if [ -r /etc/os-release ]; then
        # shellcheck disable=SC1091
        . /etc/os-release
        OS_ID="${ID:-unknown}"
        OS_VER="${VERSION_ID:-0}"
        OS_PRETTY="${PRETTY_NAME:-$OS_ID $OS_VER}"
    fi
    ARCH="$(uname -m)"
    case "$ARCH" in
        x86_64 | amd64)  GOARCH="amd64" ;;
        aarch64 | arm64) GOARCH="arm64" ;;
        armv7l | armv6l) GOARCH="armv6l" ;;
        *)               GOARCH="" ;;
    esac
}

apt_install() {
    export DEBIAN_FRONTEND=noninteractive
    if [ "${PINGIFY_APT_UPDATED:-}" != "1" ]; then
        apt-get update -qq >/dev/null 2>&1 || warn "apt-get update reported a problem, continuing"
        PINGIFY_APT_UPDATED=1
    fi
    apt-get install -y -qq "$@" >/dev/null 2>&1
}

ensure_deps() {
    local missing=()
    have curl   || missing+=(curl)
    have tar    || missing+=(tar)
    have ip     || missing+=(iproute2)
    have ss     || missing+=(iproute2)
    have base64 || missing+=(coreutils)
    if [ ${#missing[@]} -gt 0 ]; then
        if have apt-get; then
            spin "installing ${missing[*]}" apt_install "${missing[@]}" \
                || warn "some packages could not be installed"
        else
            warn "please install manually: ${missing[*]}"
        fi
    fi
    mkdir -p "$BASE_DIR" "$STATE_DIR"
    chmod 700 "$BASE_DIR"
}

# Prints the minor version of a Go toolchain, e.g. 22 for go1.22.2, or 0 when
# the binary is unusable or predates the 1.x scheme.
go_version_minor() {
    local v major rest minor
    v="$("$1" version 2>/dev/null | awk '{print $3}')"   # e.g. go1.22.2
    v="${v#go}"
    major="${v%%.*}"; rest="${v#*.}"; minor="${rest%%.*}"
    case "$major.$minor" in
        1.*[!0-9]* | 1.) printf '0'; return ;;
        1.*) printf '%s' "$minor" ;;
        *)   printf '0' ;;
    esac
}

find_go() {
    local cand
    for cand in "$(command -v go 2>/dev/null)" /usr/local/go/bin/go /usr/lib/go/bin/go; do
        [ -n "$cand" ] && [ -x "$cand" ] || continue
        if [ "$(go_version_minor "$cand")" -ge "$GO_MIN_MINOR" ] 2>/dev/null; then
            GO_BIN="$cand"; return 0
        fi
    done
    for cand in /usr/lib/go-*/bin/go; do
        [ -x "$cand" ] || continue
        if [ "$(go_version_minor "$cand")" -ge "$GO_MIN_MINOR" ] 2>/dev/null; then
            GO_BIN="$cand"; return 0
        fi
    done
    return 1
}

install_go_tarball() {
    [ -n "$GOARCH" ] || { fail "unsupported CPU architecture: $ARCH"; return 1; }
    local ver=""
    ver=$(curl -fsS --max-time 8 "https://go.dev/VERSION?m=text" 2>/dev/null | head -n1)
    case "$ver" in go1.*) ;; *) ver="$GO_FALLBACK" ;; esac
    info "downloading $ver for $GOARCH"
    if ! curl -fL --retry 2 --max-time 300 -o /tmp/pingify-go.tgz \
         "https://go.dev/dl/${ver}.linux-${GOARCH}.tar.gz"; then
        fail "could not download the Go toolchain"
        dim "this is only the fallback path - see Update Core for other options"
        return 1
    fi
    rm -rf /usr/local/go
    tar -C /usr/local -xzf /tmp/pingify-go.tgz || return 1
    rm -f /tmp/pingify-go.tgz
    [ -x /usr/local/go/bin/go ] || return 1
    GO_BIN="/usr/local/go/bin/go"
    return 0
}

ensure_go() {
    if find_go; then
        dim "using $("$GO_BIN" version)"
        return 0
    fi
    info "no suitable Go toolchain here (need 1.${GO_MIN_MINOR} or newer)"
    if have apt-get; then
        spin "installing golang-go from the distro" apt_install golang-go
        find_go && { dim "using $("$GO_BIN" version)"; return 0; }
    fi
    install_go_tarball || return 1
    dim "using $("$GO_BIN" version)"
    return 0
}
