#!/usr/bin/env bash
# =============================================================================
#  Pingify - point-to-point tunnel manager for Iran <-> Kharej server pairs
#  https://github.com/GreatTeejay/Pingify
#
#  This file is generated by build.sh: it bundles the manager and the whole Go
#  core source, so a single file is everything either server needs.
#  Edit parts/*.sh and the Go tree, then run build.sh - never edit Pingify.sh.
# =============================================================================

set -o pipefail

PINGIFY_VERSION="2.3.0"
PINGIFY_REPO="${PINGIFY_REPO:-GreatTeejay/Pingify}"

# ---------------------------------------------------------------------------
# what this terminal can do
#
# Colour only when somebody is looking. Box drawing degrades to ASCII on a
# console that is not talking UTF-8, so a bare serial session still renders
# something sane. The width follows the window, between 60 and 100 columns,
# and the frames stop at 68 however wide the window is: a box pulled across a
# two hundred column terminal is a box the eye cannot follow.
# ---------------------------------------------------------------------------

ui_detect() {
    UI_COLOR=8
    UI_GLYPH=ascii
    case "${TERM:-dumb}" in dumb | "") UI_COLOR=none ;; esac
    [ -n "${NO_COLOR:-}" ] && UI_COLOR=none
    [ -t 1 ] || UI_COLOR=none
    if [ "$UI_COLOR" != none ] && [ "$(tput colors 2>/dev/null || echo 0)" -ge 256 ]; then
        UI_COLOR=256
    fi
    case "${LC_ALL:-${LC_CTYPE:-${LANG:-}}}" in
    *[Uu][Tt][Ff]*) UI_GLYPH=utf8 ;;
    esac
    [ -n "${PINGIFY_ASCII:-}" ] && UI_GLYPH=ascii
    # A locale that names UTF-8 but is not installed - LANG carried over ssh
    # from a laptop to a server that never generated it - leaves bash
    # counting bytes, so every box drawn with glyphs comes out shredded.
    # If this shell cannot see one glyph as one character, draw in ASCII.
    # Every measurement of text below is made under a UTF-8 character type
    # that this bash can actually use: the session's own if it works, one of
    # the two every server has otherwise. With none, the glyphs are ASCII.
    UI_CTYPE=
    local l
    for l in "${LC_ALL:-}" "${LC_CTYPE:-}" "${LANG:-}" C.UTF-8 C.utf8 en_US.UTF-8; do
        [ -n "$l" ] || continue
        ui_mb_ok "$l" 2>/dev/null && { UI_CTYPE=$l; break; }
    done
    [ -n "$UI_CTYPE" ] || UI_GLYPH=ascii
    PINGIFY_UTF8=0
    [ "$UI_GLYPH" = utf8 ] && PINGIFY_UTF8=1

    UI_TERM=${PINGIFY_WIDTH:-$(tput cols 2>/dev/null || echo 80)}
    case "$UI_TERM" in '' | *[!0-9]*) UI_TERM=80 ;; esac
    [ "$UI_TERM" -gt 120 ] && UI_TERM=120
    [ "$UI_TERM" -lt 40 ] && UI_TERM=40
    UI_W=$UI_TERM
    [ "$UI_W" -gt 68 ] && UI_W=68

    ui_palette
    ui_glyphs
}

# ui_mb_ok says whether bash sees one glyph as one character under a locale.
ui_mb_ok() {
    local LC_ALL=$1 probe='─'
    [ "${#probe}" = 1 ]
}

ui_palette() {
    if [ "$UI_COLOR" = none ]; then
        C_OFF= C_B= C_DIM= C_RED= C_GRN= C_YEL= C_BLU= C_MAG= C_CYN= C_GRY=
    else
        C_OFF=$'\033[0m' C_B=$'\033[1m' C_DIM=$'\033[2m'
        C_RED=$'\033[31m' C_GRN=$'\033[32m' C_YEL=$'\033[33m'
        C_BLU=$'\033[34m' C_MAG=$'\033[35m' C_CYN=$'\033[36m'
        C_GRY=$'\033[90m'
        # Raw cyan is unreadable on a white terminal; with 256 colours the
        # accent is a desaturated teal instead.
        [ "$UI_COLOR" = 256 ] && C_CYN=$'\033[38;5;37m'
    fi
    # The same colours by the role they play, which is how the screens that
    # report on a tunnel name them.
    C_ACCENT=$C_CYN C_OK=$C_GRN C_WARN=$C_YEL C_BAD=$C_RED
    C_MUTE=$C_GRY C_KEY=$C_DIM C_RULE=$C_GRY C_ADDR=$C_CYN
}

ui_glyphs() {
    if [ "$UI_GLYPH" = utf8 ]; then
        BX_H='─' BX_V='│' BX_TL='╭' BX_TR='╮' BX_BL='╰' BX_BR='╯'
        BX_DOT='·' BX_ARR='▸' BX_ON='●' BX_OFF='○'
        MK_OK='✓' MK_NO='✗' MK_WARN='!'
        G_ARROW='→' G_BOTH='⇄' G_CUT='…' G_DASH='—'
    else
        BX_H='-' BX_V='|' BX_TL='+' BX_TR='+' BX_BL='+' BX_BR='+'
        BX_DOT='.' BX_ARR='>' BX_ON='*' BX_OFF='o'
        MK_OK='+' MK_NO='x' MK_WARN='!'
        G_ARROW='->' G_BOTH='<->' G_CUT='~' G_DASH='-'
    fi
    G_H=$BX_H G_V=$BX_V G_TL=$BX_TL G_TR=$BX_TR G_BL=$BX_BL G_BR=$BX_BR
    G_CUR=$BX_ARR G_ITEM=$BX_ARR G_DOT=$BX_DOT G_ON=$BX_ON G_OFF=$BX_OFF
    G_OK=$MK_OK G_BAD=$MK_NO G_WARN=$MK_WARN
}

# ---------------------------------------------------------------------------
# measuring and cutting text
# ---------------------------------------------------------------------------

rep() {
    local out
    printf -v out '%*s' "$2" ''
    printf '%s' "${out// /$1}"
}
repeat() { rep "$1" "$2"; }

# vislen is how many columns a string occupies once the escape codes are
# gone. Columns, not characters: a CJK glyph is two and a combining mark is
# none. Parameter expansion rather than sed, because this runs once per cell
# and a subprocess per cell is how a menu comes to take a second over ssh.
vislen() {
    local LC_ALL=${UI_CTYPE:-C} s=$1 out= n i ch cp
    while [ -n "$s" ]; do
        case $s in
        $'['*)
            s=${s#$'['}
            s=${s#*m}
            continue
            ;;
        esac
        out=$out${s:0:1}
        s=${s:1}
    done
    n=${#out}
    # Bash counts characters; correct for the ones that are not one column.
    # By code point rather than by a bracket range: in en_US.UTF-8 a range
    # is collated, not ordered, and a box-drawing glyph fell inside the CJK
    # range on a server abroad, so every frame there came out shredded.
    for ((i = 0; i < ${#out}; i++)); do
        ch=${out:i:1}
        printf -v cp '%d' "'$ch" 2>/dev/null || cp=0
        [ "$cp" -lt 768 ] && continue
        if ((cp <= 879 || (cp >= 1611 && cp <= 1631) || (cp >= 8204 && cp <= 8207))); then
            n=$((n - 1))
        elif (((cp >= 4352 && cp <= 4447) || (cp >= 11904 && cp <= 42191) || (cp >= 44032 && cp <= 55203) ||
            (cp >= 63744 && cp <= 64255) || (cp >= 65072 && cp <= 65103) || (cp >= 65280 && cp <= 65376) ||
            (cp >= 65504 && cp <= 65510) || (cp >= 127744 && cp <= 129791))); then
            n=$((n + 1))
        fi
    done
    printf '%s' "$n"
}

# trunc_to cuts a string to a width and marks that it did. A value that does
# not fit and is printed anyway takes the next column's place.
trunc_to() {
    local LC_ALL=${UI_CTYPE:-C} s=$1 w=$2 cut
    [ "$(vislen "$s")" -le "$w" ] && { printf '%s' "$s"; return; }
    cut=$((w - 1))
    [ "$cut" -lt 1 ] && cut=1
    printf '%s%s' "${s:0:cut}" "$G_CUT"
}

pad_to() {
    local s n
    s=$(trunc_to "$1" "$2")
    n=$(vislen "$s")
    printf '%s%*s' "$s" "$(($2 - n))" ''
}

# ---------------------------------------------------------------------------
# colour with a meaning
#
# An address is the thing people copy, compare and mistype, so it gets a
# colour of its own. A round trip is banded where an Iran <-> abroad path
# changes character: under 100 ms is a nearby datacentre behaving, 100-200
# is usable but felt, over 200 is a long way round or a path in trouble. A
# thing that cannot be measured is grey, never red: red means "this path is
# slow", not "there is no path".
# ---------------------------------------------------------------------------

addr_tint() { printf '%s%s%s' "$C_ADDR" "$1" "$C_OFF"; }
addr_text() { addr_tint "$1"; }

rtt_colour() {
    local ms=${1%ms}
    ms=${ms%%.*}
    case $ms in '' | *[!0-9]*) printf '%s' "$C_MUTE"; return ;; esac
    if [ "$ms" -lt 100 ]; then printf '%s' "$C_OK"
    elif [ "$ms" -lt 200 ]; then printf '%s' "$C_WARN"
    else printf '%s' "$C_BAD"; fi
}
rtt_tint() { printf '%s%s%s' "$(rtt_colour "$1")" "$1" "$C_OFF"; }
rtt_slow() {
    local ms=${1%ms}
    ms=${ms%%.*}
    case $ms in '' | *[!0-9]*) return 1 ;; esac
    [ "$ms" -ge 200 ]
}

# A tunnel carrying nothing is not a slow tunnel: nobody is using it. Below a
# megabit this is grey, and the colours start once there is traffic.
rate_colour() {
    case $1 in
    '' | *[!0-9.]*) printf '%s' "$C_MUTE" ;;
    *) if [ "${1%%.*}" -lt 1 ]; then printf '%s' "$C_MUTE"
       elif [ "${1%%.*}" -ge 100 ]; then printf '%s' "$C_OK"
       elif [ "${1%%.*}" -ge 10 ]; then printf '%s' "$C_WARN"
       else printf '%s' "$C_BAD"; fi ;;
    esac
}

# ---------------------------------------------------------------------------
# drawing primitives
# ---------------------------------------------------------------------------

# fill_to writes a line and fills the rest of the width with a glyph, so
# every rule and every box edge is measured rather than counted.
fill_to() {
    local text=$1 glyph=$2 tail=${3:-} n
    n=$((UI_W - $(vislen "$text") - $(vislen "$tail")))
    [ "$n" -lt 0 ] && n=0
    printf '%s%s%s%s%s' "$text" "$C_RULE" "$(rep "$glyph" "$n")" "$tail" "$C_OFF"
}

# A panel carries its title in the top border, so a screen full of them reads
# as a list of labelled blocks rather than a wall of rules.
panel() {
    if [ -z "${1:-}" ]; then
        printf '%s\n' "$(fill_to "  $C_RULE$BX_TL" "$BX_H" "$BX_TR")"
        return
    fi
    printf '%s\n' "$(fill_to "  $C_RULE$BX_TL$BX_H$C_OFF $C_CYN$C_B$1$C_OFF " "$BX_H" "$BX_TR")"
}
panel_open() { panel "$1"; }
panel_top() { panel ""; }
panel_end() { printf '%s\n' "$(fill_to "  $C_RULE$BX_BL" "$BX_H" "$BX_BR")"; }
panel_close() { panel_end; }

# One line inside a box, cut to fit: a value that overran pushed the closing
# bar off the end and shredded the panel.
panel_row() {
    local inner=$((UI_W - 6))
    printf '  %s%s%s %s %s%s%s\n' \
        "$C_RULE" "$BX_V" "$C_OFF" "$(pad_to "$1" "$inner")" "$C_RULE" "$BX_V" "$C_OFF"
}

# panel_field <label> <value> [label2] [value2] - a boxed key and value, two
# aligned columns in one row when a second pair is given.
UI_PANELW=13
panel_field() {
    local s
    s="$(pad_to "${C_DIM}$1${C_OFF}" "$UI_PANELW")  ${C_B}$2${C_OFF}"
    if [ -n "${3:-}" ]; then
        s="$(pad_to "$s" 32)$(pad_to "${C_DIM}$3${C_OFF}" 11) ${C_B}$4${C_OFF}"
    fi
    panel_row "$s"
}

# field is the same pair on a plain screen, outside any box.
UI_KEYW=11
field() {
    printf '    %s%s%s  %s\n' \
        "$C_KEY" "$(pad_to "$1" "$UI_KEYW")" "$C_OFF" \
        "$(trunc_to "$2" $((UI_W - UI_KEYW - 8)))"
}

# row prints cells padded to the widths in UI_COLS, which the caller sets
# once, so a header and its rows cannot drift apart.
row() {
    local i=0 out= cell
    for cell in "$@"; do
        out=$out$(pad_to "$cell" "${UI_COLS[i]:-12}")'  '
        i=$((i + 1))
    done
    out=${out%  }
    printf '   %s\n' "$(trunc_to "$out" $((UI_W - 3)))"
}

say()  { printf '%s\n' "$*"; }
blank() { printf '\n'; }
info() { printf '  %s%s%s %s\n' "$C_CYN" "$BX_ARR" "$C_OFF" "$*"; }
ok()   { printf '  %s%s%s %s\n' "$C_GRN" "$MK_OK" "$C_OFF" "$*"; }
warn() { printf '  %s%s%s %s\n' "$C_YEL" "$MK_WARN" "$C_OFF" "$*"; }
fail() { printf '  %s%s%s %s\n' "$C_RED" "$MK_NO" "$C_OFF" "$*"; }
bad()  { fail "$@"; }
dim()  { printf '    %s%s%s\n' "$C_DIM" "$*" "$C_OFF"; }
# fix is the line under a failure that says what to do about it.
fix()  { printf '      %s%s fix:%s %s\n' "$C_CYN" "$BX_ARR" "$C_OFF" "$*"; }
die()  { printf '\n  %s%s%s %s\n\n' "$C_RED" "$MK_NO" "$C_OFF" "$*" >&2; exit 1; }

# rule draws a horizontal line, with a title inside it when given one.
rule() {
    if [ -z "${1:-}" ]; then
        printf '  %s%s%s\n' "$C_GRY" "$(rep "$BX_H" "$UI_W")" "$C_OFF"
        return
    fi
    head2 "$1"
}

# A section heading whose rule runs out to the panel width.
head2() {
    local t=" $1 " n
    n=$(vislen "$t")
    printf '\n  %s%s%s%s%s%s%s\n\n' \
        "$C_GRY" "$BX_H$BX_H" "$C_OFF$C_CYN$C_B" "$t" "$C_OFF$C_GRY" \
        "$(rep "$BX_H" $((UI_W - n - 4)))" "$C_OFF"
}

# A label above a run of related menu entries.
group() { printf '\n  %s%s%s\n' "$C_DIM$C_B" "$1" "$C_OFF"; }

# item <key> <label> [hint] - one line of a menu. The label column grows if a
# label outruns it, so a long one can never end up glued to its hint.
UI_ITEMW=24
item() {
    local w=$UI_ITEMW n hint=${3:-} hw
    n=$(vislen "$2")
    [ "$n" -ge "$w" ] && w=$((n + 2))
    hw=$((UI_TERM - w - 9))
    if [ -n "$hint" ] && [ "$hw" -ge 6 ]; then
        printf '   %s%2s%s %s%s%s %s%s%s%s\n' \
            "$C_CYN$C_B" "$1" "$C_OFF" "$C_GRY" "$BX_ARR" "$C_OFF" \
            "$(pad_to "$2" "$w")" "$C_DIM" "$(trunc_to "$hint" "$hw")" "$C_OFF"
    else
        printf '   %s%2s%s %s%s%s %s\n' \
            "$C_CYN$C_B" "$1" "$C_OFF" "$C_GRY" "$BX_ARR" "$C_OFF" \
            "$(trunc_to "$2" $((UI_TERM - 9)))"
    fi
}
# item2 is the same line with the current value of a setting on the right.
item2() { item "$@"; }

# state_badge <on|off> - a coloured on/off badge for toggles.
state_badge() {
    if [ "$1" = on ]; then printf '%s%s on%s' "$C_GRN" "$BX_ON" "$C_OFF"
    else printf '%s%s off%s' "$C_GRY" "$BX_OFF" "$C_OFF"; fi
}

# state_dot is the one glyph that says whether a thing is doing its job.
# Running is the only green; not known is grey, because not known is not
# broken.
state_dot() {
    case $1 in
    running) printf '%s%s%s' "$C_OK" "$BX_ON" "$C_OFF" ;;
    idle) printf '%s%s%s' "$C_WARN" "$BX_ON" "$C_OFF" ;;
    stopped) printf '%s%s%s' "$C_WARN" "$BX_OFF" "$C_OFF" ;;
    *) printf '%s%s%s' "$C_MUTE" "$BX_OFF" "$C_OFF" ;;
    esac
}

# ---------------------------------------------------------------------------
# the banner
#
# The name sits in its own frame, centred, so the page opens with one object
# rather than six lines floating above a rule. Two renderings and no third: a
# terminal without a UTF-8 locale draws the block glyphs as question marks.
# ---------------------------------------------------------------------------

banner_art() {
    if [ "$UI_GLYPH" = utf8 ]; then
        printf '%s\n' \
            '██████╗ ██╗███╗   ██╗ ██████╗ ██╗███████╗██╗   ██╗' \
            '██╔══██╗██║████╗  ██║██╔════╝ ██║██╔════╝╚██╗ ██╔╝' \
            '██████╔╝██║██╔██╗ ██║██║  ███╗██║█████╗   ╚████╔╝ ' \
            '██╔═══╝ ██║██║╚██╗██║██║   ██║██║██╔══╝    ╚██╔╝  ' \
            '██║     ██║██║ ╚████║╚██████╔╝██║██║        ██║   ' \
            '╚═╝     ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝╚═╝        ╚═╝   '
    else
        printf '%s\n' \
            ' ____   ___  _   _   ____  ___  _____ __   __' \
            '|  _ \ |_ _|| \ | | / ___||_ _||  ___|\ \ / /' \
            '| |_) | | | |  \| || |  _  | | | |_    \ V / ' \
            '|  __/  | | | |\  || |_| | | | |  _|    | |  ' \
            '|_|    |___||_| \_| \____||___||_|      |_|  '
    fi
}

banner_line() {
    local text=$1 colour=$2 inner=$((UI_W - 6)) pad
    pad=$(((inner - $(vislen "$text")) / 2))
    [ "$pad" -lt 0 ] && pad=0
    panel_row "$(printf '%*s%s%s%s' "$pad" '' "$colour" "$text" "$C_OFF")"
}

# wipe clears the screen at the top of a screen, and only there. It moves
# the cursor home and erases what is on the screen without touching the
# scrollback, so everything drawn before is still a page up.
wipe() {
    [ -t 1 ] || return 0
    [ "$UI_COLOR" = none ] && return 0
    printf '\033[H\033[2J'
}

banner() {
    local extra=${1:-} line
    wipe
    blank
    panel ""
    while IFS= read -r line; do
        banner_line "$line" "$C_CYN$C_B"
    done < <(banner_art)
    banner_line "by Teejay   $BX_DOT   Iran $BX_ARR Kharej tunnel" "$C_DIM"
    [ -n "$extra" ] && banner_line "$extra" "$C_DIM"
    panel_end
}
screen_top() { banner; }

# ---------------------------------------------------------------------------
# the wizard
#
# The steps run down one page. Nothing is cleared between them, so the
# answers already given stay on screen above the question being asked - which
# is what you want when you are copying the same numbers onto a second
# server. Half a wizard is not a tunnel, so q at any question leaves.
# ---------------------------------------------------------------------------

WIZ_STEP=0
WIZ_ACTIVE=0
WIZ_QUIT=0
wiz_reset() { WIZ_STEP=0; WIZ_ACTIVE=1; WIZ_QUIT=0; }
wiz_end()   { WIZ_ACTIVE=0; WIZ_QUIT=0; }
wiz_quit()  { [ "${WIZ_QUIT:-0}" = 1 ]; }

# wiz <title> [subtitle] - open a step.
wiz() {
    WIZ_STEP=$((WIZ_STEP + 1))
    local t="$WIZ_STEP $BX_DOT $1 " n
    n=$(vislen " $t")
    printf '\n  %s%s%s%s%s%s%s\n\n' \
        "$C_GRY" "$BX_H$BX_H " "$C_OFF$C_CYN$C_B" "$t" "$C_OFF$C_GRY" \
        "$(rep "$BX_H" $((UI_W - n - 5)))" "$C_OFF"
    [ -n "${2:-}" ] && { dim "$2"; blank; }
    return 0
}

# choice <key> <name> <hint> - one option, name and reason on the same line.
# CHOICE_DEF marks the one enter picks, on the line itself.
CHOICE_DEF=""
choice() {
    local mark="   " hint=${3:-}
    if [ "$1" = "$CHOICE_DEF" ]; then
        mark="${C_GRN}${BX_ARR}${C_OFF}  "
        hint="${hint}${hint:+  }${C_GRN}(default)${C_OFF}"
    fi
    printf '  %s%s%2s%s  %s  %s%s%s\n' \
        "$mark" "$C_CYN$C_B" "$1" "$C_OFF" \
        "$(pad_to "${C_B}$2${C_OFF}" 14)" \
        "$C_DIM" "$(trunc_to "$hint" $((UI_TERM - 24)))" "$C_OFF"
}

pause() {
    printf '\n'
    read -rsp "  ${C_DIM}press enter${C_OFF}" _ || true
    printf '\n'
}

# ---------------------------------------------------------------------------
# asking
#
# ask VAR "prompt" ["default"] [validator]
#
# A validator prints why it refused and returns non-zero; the reason is shown
# under the prompt and the question is asked again. q leaves, and once the
# wizard is leaving every later question returns without asking, so it
# unwinds instead of finishing. End of input is not an answer to wait for: a
# piped script that runs out stops here rather than asking for ever.
#
# The locals are prefixed because bash scopes locals dynamically: a caller
# that names its own variable `def` and passed it here would have had it
# overwritten by this function's own.
# ---------------------------------------------------------------------------

ask() {
    local _pk_var=$1 _pk_prompt=$2 _pk_def=${3:-} _pk_check=${4:-} _pk_in _pk_err _pk_rc
    [ "${WIZ_QUIT:-0}" = 1 ] && return 1
    while :; do
        _pk_rc=0
        if [ -n "$_pk_def" ]; then
            read -rp "  ${C_CYN}${BX_ARR}${C_OFF} ${_pk_prompt} ${C_DIM}[${_pk_def}]${C_OFF}${C_B}:${C_OFF} " _pk_in || _pk_rc=1
        else
            read -rp "  ${C_CYN}${BX_ARR}${C_OFF} ${_pk_prompt}${C_B}:${C_OFF} " _pk_in || _pk_rc=1
        fi
        # Standard input has ended. No answer is coming, and a default taken
        # here would answer every remaining question by itself.
        if [ "$_pk_rc" = 1 ]; then
            [ "${WIZ_ACTIVE:-0}" = 1 ] && WIZ_QUIT=1
            return 1
        fi
        [ -z "$_pk_in" ] && _pk_in=$_pk_def
        case $_pk_in in
        q | Q | quit) WIZ_QUIT=1; return 1 ;;
        esac
        if [ -z "$_pk_check" ]; then
            printf -v "$_pk_var" '%s' "$_pk_in"
            return 0
        fi
        if _pk_err=$("$_pk_check" "$_pk_in" 2>&1); then
            printf -v "$_pk_var" '%s' "$_pk_in"
            return 0
        fi
        fail "${_pk_err:-not a valid answer}"
    done
}

# pick VAR "prompt" DEFAULT N - one of the numbers 1..N, and nothing else.
# An empty default means the question has no default: which server this is,
# what transport to speak - an empty enter that quietly means "the first one"
# is how somebody ends up with a tunnel they did not choose.
pick() {
    # Its own name for the answer: ask declares a local of its own with the
    # usual one, and bash scopes locals dynamically, so an answer written
    # into that name would land in ask's copy and this loop would never end.
    local _pk_var=$1 _pk_prompt=$2 _pk_def=${3:-} _pk_n=$4 _pk_ans
    while :; do
        ask _pk_ans "$_pk_prompt" "$_pk_def" v_raw || return 1
        case $_pk_ans in
        '') fail "this one has no default - choose 1 to $_pk_n"; continue ;;
        *[!0-9]*) ;;
        *) if [ "$_pk_ans" -ge 1 ] && [ "$_pk_ans" -le "$_pk_n" ]; then
               printf -v "$_pk_var" '%s' "$_pk_ans"
               return 0
           fi ;;
        esac
        fail "not one of the options - choose 1 to $_pk_n"
    done
}

# confirm "question" [y|n] - the default is no unless said otherwise.
confirm() {
    local _pk_prompt=$1 _pk_def=${2:-n} _pk_in _pk_hint='[y/N]'
    [ "$_pk_def" = y ] && _pk_hint='[Y/n]'
    [ "${WIZ_QUIT:-0}" = 1 ] && return 1
    while :; do
        read -rp "  ${C_YEL}?${C_OFF} $_pk_prompt ${C_DIM}${_pk_hint}${C_OFF}${C_B}:${C_OFF} " _pk_in || return 1
        [ -z "$_pk_in" ] && _pk_in=$_pk_def
        case $_pk_in in
        y | Y | yes | YES) return 0 ;;
        n | N | no | NO) return 1 ;;
        q | Q) WIZ_QUIT=1; return 1 ;;
        esac
    done
}

# confirm_yes is confirm with the answer already leaning the right way: by the
# time it is asked, everything has been reviewed and the expected reply is yes.
confirm_yes() { confirm "$1" y; }

# menu_key VAR - the number a screen is waiting for. A line, not a keystroke,
# so a screen with more than ten things on it can be answered, and so the
# answer arrives the same way when there is no terminal at all.
menu_key() {
    local _pk_var=$1 _pk_in
    read -rp "  ${C_CYN}${BX_ARR}${C_OFF} select${C_B}:${C_OFF} " _pk_in || return 1
    _pk_in=${_pk_in#"${_pk_in%%[![:space:]]*}"}
    _pk_in=${_pk_in%"${_pk_in##*[![:space:]]}"}
    printf -v "$_pk_var" '%s' "$_pk_in"
}

# ---------------------------------------------------------------------------
# validators
# ---------------------------------------------------------------------------

v_any() { [ -n "$1" ] || { echo "say something"; return 1; }; }
v_raw() { return 0; }

v_host() {
    local h=$1 o
    [ -n "$h" ] || { echo "an address is required"; return 1; }
    if [[ $h =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        for o in ${h//./ }; do
            [ "$o" -le 255 ] || { echo "$h: $o is not part of an address"; return 1; }
        done
        return 0
    fi
    case $h in
    *[!a-zA-Z0-9.-]* | .* | *. | *..*) echo "$h is not an address or a hostname"; return 1 ;;
    *.*) return 0 ;;
    esac
    echo "$h is not an address or a hostname"
    return 1
}

v_port() {
    case $1 in '' | *[!0-9]*) echo "a port is a number"; return 1 ;; esac
    { [ "$1" -ge 1 ] && [ "$1" -le 65535 ]; } || { echo "a port is between 1 and 65535"; return 1; }
}

v_octet() {
    case $1 in '' | *[!0-9]*) echo "a number from 1 to 254"; return 1 ;; esac
    { [ "$1" -ge 1 ] && [ "$1" -le 254 ]; } || { echo "between 1 and 254"; return 1; }
}

v_mtu() {
    case $1 in '' | *[!0-9]*) echo "an mtu is a number"; return 1 ;; esac
    { [ "$1" -ge 576 ] && [ "$1" -le 9000 ]; } ||
        { echo "the core takes 576 to 9000; 1320 is what works on most paths"; return 1; }
}

v_token() {
    [ "${#1}" -ge 8 ] || { echo "the core wants at least eight characters"; return 1; }
}

v_name() {
    case $1 in '' | *[!a-zA-Z0-9_-]*) echo "letters, digits, dash and underscore"; return 1 ;; esac
    [ "${#1}" -le 24 ] || { echo "keep it under twenty-five characters"; return 1; }
}

v_number() {
    case $1 in '' | *[!0-9]*) echo "a number"; return 1 ;; esac
}

# ---------------------------------------------------------------------------
# waiting
# ---------------------------------------------------------------------------

# spin "message" command... - runs the command and shows that something is
# happening, so a download or a build never looks frozen. Nothing is drawn
# when nobody is watching.
spin() {
    local msg=$1
    shift
    if [ ! -t 2 ] || [ "$UI_COLOR" = none ]; then "$@"; return $?; fi
    "$@" &
    local pid=$! i=0 frames='|/-\'
    while kill -0 "$pid" 2>/dev/null; do
        printf '\r  %s%s%s %s ' "$C_CYN" "${frames:i++%4:1}" "$C_OFF" "$msg" >&2
        sleep 0.1
    done
    wait "$pid"
    local rc=$?
    printf '\r%*s\r' $((${#msg} + 8)) '' >&2
    return $rc
}

ui_detect
trap 'ui_detect' WINCH
