#!/usr/bin/env bash
# =============================================================================
#  Pingify - point-to-point tunnel manager for Iran <-> Kharej server pairs
#  https://github.com/GreatTeejay/Pingify
#
#  This file is generated by build.sh: it bundles the manager and the whole Go
#  core source, so a single file is everything either server needs.
#  Edit parts/*.sh and the Go tree, then run build.sh - never edit Pingify.sh.
# =============================================================================

set -o pipefail

PINGIFY_VERSION="1.1.1"
PINGIFY_REPO="${PINGIFY_REPO:-GreatTeejay/Pingify}"

# ---------------------------------------------------------------------------
# what this terminal can do
#
# Colour only when somebody is looking. Box drawing degrades to ASCII on a
# console that is not talking UTF-8, so a bare serial session still renders
# something sane. The width follows the window, between 40 and 120 columns,
# and the frames stop at 68 however wide the window is: a box pulled across a
# two hundred column terminal is a box the eye cannot follow.
# ---------------------------------------------------------------------------

ui_detect() {
    UI_COLOR=8
    UI_GLYPH=ascii
    case "${TERM:-dumb}" in dumb | "") UI_COLOR=none ;; esac
    [ -n "${NO_COLOR:-}" ] && UI_COLOR=none
    # A held screen is still going to the terminal: a window resized while
    # one is drawn must not take the colour away for the rest of the session.
    [ -t 1 ] || [ -n "${UI_HELD:-}" ] || UI_COLOR=none
    if [ "$UI_COLOR" != none ] && [ "$(tput colors 2>/dev/null || echo 0)" -ge 256 ]; then
        UI_COLOR=256
    fi
    case "${LC_ALL:-${LC_CTYPE:-${LANG:-}}}" in
    *[Uu][Tt][Ff]*) UI_GLYPH=utf8 ;;
    esac
    [ -n "${PINGIFY_ASCII:-}" ] && UI_GLYPH=ascii
    # A locale that names UTF-8 but is not installed - LANG carried over ssh
    # from a laptop to a server that never generated it - leaves bash
    # counting bytes, so every box drawn with glyphs comes out shredded.
    # If this shell cannot see one glyph as one character, draw in ASCII.
    # Every measurement of text below is made under a UTF-8 character type
    # that this bash can actually use: the session's own if it works, one of
    # the two every server has otherwise. With none, the glyphs are ASCII.
    UI_CTYPE=
    local l
    for l in "${LC_ALL:-}" "${LC_CTYPE:-}" "${LANG:-}" C.UTF-8 C.utf8 en_US.UTF-8; do
        [ -n "$l" ] || continue
        ui_mb_ok "$l" 2>/dev/null && { UI_CTYPE=$l; break; }
    done
    [ -n "$UI_CTYPE" ] || UI_GLYPH=ascii
    PINGIFY_UTF8=0
    [ "$UI_GLYPH" = utf8 ] && PINGIFY_UTF8=1

    UI_TERM=${PINGIFY_WIDTH:-$(tput cols 2>/dev/null || echo 80)}
    case "$UI_TERM" in '' | *[!0-9]*) UI_TERM=80 ;; esac
    [ "$UI_TERM" -gt 120 ] && UI_TERM=120
    [ "$UI_TERM" -lt 40 ] && UI_TERM=40
    UI_W=$UI_TERM
    [ "$UI_W" -gt 68 ] && UI_W=68
    # Text folds wider than the frames: the sentences on these screens were
    # written seventy-six columns to a line, and folded at the frames' 64
    # every one of those left its last word alone on a line of its own.
    UI_TX=$UI_TERM
    [ "$UI_TX" -gt 80 ] && UI_TX=80

    ui_palette
    ui_glyphs
}

# ui_mb_ok says whether bash sees one glyph as one character under a locale.
ui_mb_ok() {
    local LC_ALL=$1 probe='─'
    [ "${#probe}" = 1 ]
}

ui_palette() {
    if [ "$UI_COLOR" = none ]; then
        C_OFF= C_B= C_DIM= C_RED= C_GRN= C_YEL= C_BLU= C_MAG= C_CYN= C_GRY=
    else
        C_OFF=$'\033[0m' C_B=$'\033[1m' C_DIM=$'\033[2m'
        C_RED=$'\033[31m' C_GRN=$'\033[32m' C_YEL=$'\033[33m'
        C_BLU=$'\033[34m' C_MAG=$'\033[35m' C_CYN=$'\033[36m'
        C_GRY=$'\033[90m'
        # Raw cyan is unreadable on a white terminal; with 256 colours the
        # accent is a desaturated teal instead.
        [ "$UI_COLOR" = 256 ] && C_CYN=$'\033[38;5;37m'
    fi
    # The same colours by the role they play, which is how the screens that
    # report on a tunnel name them.
    C_ACCENT=$C_CYN C_OK=$C_GRN C_WARN=$C_YEL C_BAD=$C_RED
    C_MUTE=$C_GRY C_KEY=$C_DIM C_RULE=$C_GRY C_ADDR=$C_CYN
}

ui_glyphs() {
    if [ "$UI_GLYPH" = utf8 ]; then
        BX_H='─' BX_V='│' BX_TL='╭' BX_TR='╮' BX_BL='╰' BX_BR='╯'
        BX_DOT='·' BX_ARR='▸' BX_ON='●' BX_OFF='○'
        MK_OK='✓' MK_NO='✗' MK_WARN='!'
        G_ARROW='→' G_BOTH='⇄' G_CUT='…' G_DASH='—'
    else
        BX_H='-' BX_V='|' BX_TL='+' BX_TR='+' BX_BL='+' BX_BR='+'
        BX_DOT='.' BX_ARR='>' BX_ON='*' BX_OFF='o'
        MK_OK='+' MK_NO='x' MK_WARN='!'
        G_ARROW='->' G_BOTH='<->' G_CUT='~' G_DASH='-'
    fi
    G_H=$BX_H G_V=$BX_V G_TL=$BX_TL G_TR=$BX_TR G_BL=$BX_BL G_BR=$BX_BR
    G_CUR=$BX_ARR G_ITEM=$BX_ARR G_DOT=$BX_DOT G_ON=$BX_ON G_OFF=$BX_OFF
    G_OK=$MK_OK G_BAD=$MK_NO G_WARN=$MK_WARN
}

# ---------------------------------------------------------------------------
# measuring and cutting text
# ---------------------------------------------------------------------------

# rep GLYPH N - N of the glyph. _rep leaves them in RP instead.
rep() { _rep "$1" "${2:-0}"; printf '%s' "$RP"; }
_rep() {
    RP=
    [ "${2:-0}" -gt 0 ] 2>/dev/null || return 0
    printf -v RP '%*s' "$2" ''
    RP=${RP// /$1}
}

# vislen is how many columns a string occupies once the escape codes are
# gone. Columns, not characters: a CJK glyph is two and a combining mark is
# none.
#
# The measuring is in _vislen, which leaves the answer in VL, and so are the
# cutting and the padding below: every cell of every menu line is measured,
# and a subshell around each measure was most of what a screen cost - 45 ms
# a menu line on a server busy with its users, over a second a screen, drawn
# visibly from the top down. vislen, trunc_to and pad_to print the same
# answers, for the callers that want them that way.
vislen() { _vislen "$1"; printf '%s' "$VL"; }
_vislen() {
    local LC_ALL=${UI_CTYPE:-C} s=$1 out= ch cp
    # The escape codes out a sequence at a time, not a character at a time.
    while [[ $s == *$'\033['* ]]; do
        out+=${s%%$'\033['*}
        s=${s#*$'\033['}
        s=${s#*m}
    done
    out+=$s
    VL=${#out}
    # Plain ASCII is a column a character, and that is nearly every string.
    [[ $out == *[![:ascii:]]* ]] || return 0
    # Bash counts characters; correct for the ones that are not one column.
    # By code point rather than by a bracket range: in en_US.UTF-8 a range
    # is collated, not ordered, and a box-drawing glyph fell inside the CJK
    # range on a server abroad, so every frame there came out shredded.
    # Only the characters past ASCII are looked at, each taken off the
    # front: indexing into a multibyte string walks it from its start every
    # time, and the banner's six lines of blocks cost a tenth of a second.
    out=${out//[[:ascii:]]/}
    while [ -n "$out" ]; do
        ch=${out:0:1}
        out=${out:1}
        printf -v cp '%d' "'$ch" 2>/dev/null || cp=0
        [ "$cp" -lt 768 ] && continue
        if ((cp <= 879 || (cp >= 1611 && cp <= 1631) || (cp >= 8204 && cp <= 8207))); then
            VL=$((VL - 1))
        elif (((cp >= 4352 && cp <= 4447) || (cp >= 11904 && cp <= 42191) || (cp >= 44032 && cp <= 55203) ||
            (cp >= 63744 && cp <= 64255) || (cp >= 65072 && cp <= 65103) || (cp >= 65280 && cp <= 65376) ||
            (cp >= 65504 && cp <= 65510) || (cp >= 127744 && cp <= 129791))); then
            VL=$((VL + 1))
        fi
    done
}

# trunc_to STRING WIDTH - the string cut to fit, with the cut marked, so a
# value that does not fit never takes the next column's place. Colour codes
# are carried through and never counted, and a cut string always ends with
# the colour reset so what was bold or dim does not run on into the next
# line. _trunc leaves it in TR.
trunc_to() { _trunc "$1" "$2"; printf '%s' "$TR"; }
_trunc() {
    local LC_ALL=${UI_CTYPE:-C} s=$1 w=$2 cut out= n=0 seen=0
    _vislen "$s"
    [ "$VL" -le "$w" ] && { TR=$s; return 0; }
    cut=$((w - 1))
    [ "$cut" -lt 1 ] && cut=1
    # No colour and nothing wider than a column: the cut is one expansion.
    if [[ $s != *$'\033'* && $s != *[![:ascii:]]* ]]; then
        TR=${s:0:cut}$G_CUT
        return 0
    fi
    while [ -n "$s" ] && [ "$n" -lt "$cut" ]; do
        case $s in
        $'\033['*)
            out=$out${s%%m*}m
            s=${s#*m}
            seen=1
            continue
            ;;
        esac
        out=$out${s:0:1}
        s=${s:1}
        n=$((n + 1))
    done
    [ "$seen" = 1 ] && out=$out$C_OFF
    TR=$out$G_CUT
}

# pad_to STRING WIDTH - cut to the width if it must be, then filled to it.
# _pad leaves it in PD.
pad_to() { _pad "$1" "$2"; printf '%s' "$PD"; }
_pad() {
    _trunc "$1" "$2"
    _vislen "$TR"
    printf -v PD '%s%*s' "$TR" "$(($2 - VL))" ''
}

# ---------------------------------------------------------------------------
# colour with a meaning
#
# An address is the thing people copy, compare and mistype, so it gets a
# colour of its own. A round trip is banded where an Iran <-> abroad path
# changes character: under 100 ms is a nearby datacentre behaving, 100-200
# is usable but felt, over 200 is a long way round or a path in trouble. A
# thing that cannot be measured is grey, never red: red means "this path is
# slow", not "there is no path".
# ---------------------------------------------------------------------------

addr_tint() { printf '%s%s%s' "$C_ADDR" "$1" "$C_OFF"; }

rtt_colour() {
    local ms=${1%ms}
    ms=${ms%%.*}
    case $ms in '' | *[!0-9]*) printf '%s' "$C_MUTE"; return ;; esac
    if [ "$ms" -lt 100 ]; then printf '%s' "$C_OK"
    elif [ "$ms" -lt 200 ]; then printf '%s' "$C_WARN"
    else printf '%s' "$C_BAD"; fi
}
rtt_tint() { printf '%s%s%s' "$(rtt_colour "$1")" "$1" "$C_OFF"; }

# ---------------------------------------------------------------------------
# drawing primitives
# ---------------------------------------------------------------------------

# fill_to writes a line and fills the rest of the width with a glyph, so
# every rule and every box edge is measured rather than counted.
fill_to() {
    local text=$1 glyph=$2 tail=${3:-} n
    _vislen "$text"
    n=$VL
    _vislen "$tail"
    n=$((UI_W - n - VL))
    [ "$n" -lt 0 ] && n=0
    _rep "$glyph" "$n"
    printf '%s%s%s%s%s' "$text" "$C_RULE" "$RP" "$tail" "$C_OFF"
}

# A panel carries its title in the top border, so a screen full of them reads
# as a list of labelled blocks rather than a wall of rules.
panel() {
    if [ -z "${1:-}" ]; then
        fill_to "  $C_RULE$BX_TL" "$BX_H" "$BX_TR"
    else
        fill_to "  $C_RULE$BX_TL$BX_H$C_OFF $C_CYN$C_B$1$C_OFF " "$BX_H" "$BX_TR"
    fi
    printf '\n'
}
panel_open() { panel "$1"; }
panel_end() { fill_to "  $C_RULE$BX_BL" "$BX_H" "$BX_BR"; printf '\n'; }
panel_close() { panel_end; }

# One line inside a box, cut to fit: a value that overran pushed the closing
# bar off the end and shredded the panel.
panel_row() {
    _pad "$1" $((UI_W - 6))
    printf '  %s%s%s %s %s%s%s\n' \
        "$C_RULE" "$BX_V" "$C_OFF" "$PD" "$C_RULE" "$BX_V" "$C_OFF"
}

# panel_field <label> <value> [label2] [value2] - a boxed key and value, two
# aligned columns in one row when a second pair is given.
UI_PANELW=13
panel_field() {
    local s inner=$((UI_W - 6))
    _pad "${C_DIM}$1${C_OFF}" "$UI_PANELW"
    s="$PD  ${C_B}$2${C_OFF}"
    if [ -n "${3:-}" ]; then
        # Two pairs share a row only when the row has room for both; below
        # that the second pair takes a row of its own rather than a letter.
        if [ "$inner" -ge 56 ]; then
            _pad "$s" $((inner / 2))
            s=$PD
            _pad "${C_DIM}$3${C_OFF}" $((UI_PANELW - 2))
            s="$s$PD ${C_B}$4${C_OFF}"
        else
            panel_row "$s"
            _pad "${C_DIM}$3${C_OFF}" "$UI_PANELW"
            s="$PD  ${C_B}$4${C_OFF}"
        fi
    fi
    panel_row "$s"
}

# field is the same pair on a plain screen, outside any box.
UI_KEYW=11
field() {
    local k
    _pad "$1" "$UI_KEYW"
    k=$PD
    _trunc "$2" $((UI_W - UI_KEYW - 8))
    printf '    %s%s%s  %s\n' "$C_KEY" "$k" "$C_OFF" "$TR"
}

# row prints cells padded to the widths in UI_COLS, which the caller sets
# once, so a header and its rows cannot drift apart.
row() {
    local i=0 out= cell
    for cell in "$@"; do
        _pad "$cell" "${UI_COLS[i]:-12}"
        out=$out$PD'  '
        i=$((i + 1))
    done
    out=${out%  }
    _trunc "$out" $((UI_TERM - 3))
    printf '   %s\n' "$TR"
}

say()  { printf '%s\n' "$*"; }
blank() { printf '\n'; }
info() { say_wrapped "  ${C_CYN}${BX_ARR}${C_OFF} " "    " "$*"; }
ok()   { say_wrapped "  ${C_GRN}${MK_OK}${C_OFF} " "    " "$*"; }
warn() { say_wrapped "  ${C_YEL}${MK_WARN}${C_OFF} " "    " "$*"; }
fail() { say_wrapped "  ${C_RED}${MK_NO}${C_OFF} " "    " "$*"; }
bad()  { fail "$@"; }
# fold WIDTH TEXT - the text broken on spaces so that no line is wider than
# WIDTH. Colour codes are carried through and not counted, so a coloured
# word does not make a short line look long. Split on single spaces, so a
# run of them written to line something up stays a run - it was closed up to
# one - and never globbed: a word was a pattern the shell expanded against
# whatever directory the menu was run from. _fold leaves it in FD.
fold() { _fold "$1" "$2"; printf '%s' "$FD"; }
_fold() {
    local w=$1 rest=$2 word line= cur=0 out= last=
    rest=${rest//$'\n'/ }
    rest=${rest//$'\t'/ }
    while [ -z "$last" ]; do
        case $rest in
        *' '*) word=${rest%% *} rest=${rest#* } ;;
        *) word=$rest last=1 ;;
        esac
        _vislen "$word"
        if [ -z "$line" ]; then
            [ -n "$word" ] && line=$word cur=$VL
        elif [ $((cur + 1 + VL)) -le "$w" ]; then
            line="$line $word" cur=$((cur + 1 + VL))
        else
            out=$out$line$'\n'
            line=$word cur=$VL
        fi
    done
    FD=$out$line
}

# say_wrapped PREFIX INDENT TEXT - one of the lines below, folded at the
# screen's width. A sentence used to run off the right edge of an eighty
# column terminal, and a wrapped fix line lost its indent, which read as a
# second item.
say_wrapped() {
    local lead=$1 pad=$2
    _fold $((UI_TX - ${#pad})) "$3"
    while [[ $FD == *$'\n'* ]]; do
        printf '%s%s\n' "$lead" "${FD%%$'\n'*}"
        FD=${FD#*$'\n'}
        lead=$pad
    done
    printf '%s%s\n' "$lead" "$FD"
}

dim()  { say_wrapped "    ${C_DIM}" "    " "$*${C_OFF}"; }
# dim_wrap LEAD SEP - dim lines from the items on standard input, one an
# item, folded at the screen's width. LEAD opens the first line and its
# width indents the rest, so a list that would run off the right edge folds
# under itself. SEP goes between items; its first word ends a folded line,
# so a comma list folds with a comma.
dim_wrap() {
    local lead=$1 sep=$2 w=$((UI_TX - 4)) lw pad line cur n=0 item tail
    _vislen "$lead"
    lw=$VL
    printf -v pad '%*s' "$lw" ''
    tail=${sep%%[[:space:]]*}
    line=$lead cur=$lw
    while IFS= read -r item; do
        [ -n "$item" ] || continue
        if [ "$n" -gt 0 ] && [ $((cur + ${#sep} + ${#item})) -gt "$w" ]; then
            dim "$line$tail"
            line="$pad$item" cur=$((lw + ${#item})) n=1
        elif [ "$n" -gt 0 ]; then
            line="$line$sep$item" cur=$((cur + ${#sep} + ${#item})) n=$((n + 1))
        else
            line="$line$item" cur=$((cur + ${#item})) n=1
        fi
    done
    [ "$n" -gt 0 ] && dim "$line"
    return 0
}
# fix is the line under a failure that says what to do about it.
fix()  { say_wrapped "      ${C_CYN}${BX_ARR} fix:${C_OFF} " "           " "$*"; }
die()  { printf '\n  %s%s%s %s\n\n' "$C_RED" "$MK_NO" "$C_OFF" "$*" >&2; exit 1; }

# rule draws a horizontal line, with a title inside it when given one.
rule() {
    if [ -z "${1:-}" ]; then
        _rep "$BX_H" "$UI_W"
        printf '  %s%s%s\n' "$C_GRY" "$RP" "$C_OFF"
        return
    fi
    head2 "$1"
}

# A section heading whose rule runs out to the panel width.
head2() {
    local t=" $1 "
    _vislen "$t"
    _rep "$BX_H" $((UI_W - VL - 4))
    printf '\n  %s%s%s%s%s%s%s\n\n' \
        "$C_GRY" "$BX_H$BX_H" "$C_OFF$C_CYN$C_B" "$t" "$C_OFF$C_GRY" "$RP" "$C_OFF"
}

# A label above a run of related menu entries.
group() { printf '\n  %s%s%s\n' "$C_DIM$C_B" "$1" "$C_OFF"; }

# item <key> <label> [hint] - one line of a menu. The label column grows if a
# label outruns it, so a long one can never end up glued to its hint.
UI_ITEMW=24
item() {
    local w=$UI_ITEMW hint=${3:-} hw label
    _vislen "$2"
    [ "$VL" -ge "$w" ] && w=$((VL + 2))
    hw=$((UI_TERM - w - 9))
    if [ -n "$hint" ] && [ "$hw" -ge 6 ]; then
        _pad "$2" "$w"
        label=$PD
        _trunc "$hint" "$hw"
        printf '   %s%2s%s %s%s%s %s%s%s%s\n' \
            "$C_CYN$C_B" "$1" "$C_OFF" "$C_GRY" "$BX_ARR" "$C_OFF" \
            "$label" "$C_DIM" "$TR" "$C_OFF"
    else
        _trunc "$2" $((UI_TERM - 9))
        printf '   %s%2s%s %s%s%s %s\n' \
            "$C_CYN$C_B" "$1" "$C_OFF" "$C_GRY" "$BX_ARR" "$C_OFF" "$TR"
    fi
}
# item2 is the same line with the current value of a setting on the right.
item2() { item "$@"; }

# state_badge <on|off> - a coloured on/off badge for toggles.
state_badge() {
    if [ "$1" = on ]; then printf '%s%s on%s' "$C_GRN" "$BX_ON" "$C_OFF"
    else printf '%s%s off%s' "$C_GRY" "$BX_OFF" "$C_OFF"; fi
}

# state_dot is the one glyph that says whether a thing is doing its job.
# Running is the only green; not known is grey, because not known is not
# broken.
state_dot() {
    case $1 in
    running) printf '%s%s%s' "$C_OK" "$BX_ON" "$C_OFF" ;;
    idle) printf '%s%s%s' "$C_WARN" "$BX_ON" "$C_OFF" ;;
    stopped) printf '%s%s%s' "$C_WARN" "$BX_OFF" "$C_OFF" ;;
    *) printf '%s%s%s' "$C_MUTE" "$BX_OFF" "$C_OFF" ;;
    esac
}

# ---------------------------------------------------------------------------
# the banner
#
# The name sits in its own frame, centred, so the page opens with one object
# rather than six lines floating above a rule. Two renderings and no third: a
# terminal without a UTF-8 locale draws the block glyphs as question marks.
# ---------------------------------------------------------------------------

banner_art() { _banner_art; printf '%s\n' "${BA[@]}"; }
_banner_art() {
    if [ "$UI_GLYPH" = utf8 ]; then
        BA=('██████╗ ██╗███╗   ██╗ ██████╗ ██╗███████╗██╗   ██╗'
            '██╔══██╗██║████╗  ██║██╔════╝ ██║██╔════╝╚██╗ ██╔╝'
            '██████╔╝██║██╔██╗ ██║██║  ███╗██║█████╗   ╚████╔╝ '
            '██╔═══╝ ██║██║╚██╗██║██║   ██║██║██╔══╝    ╚██╔╝  '
            '██║     ██║██║ ╚████║╚██████╔╝██║██║        ██║   '
            '╚═╝     ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝╚═╝        ╚═╝   ')
    else
        BA=(' ____   ___  _   _   ____  ___  _____ __   __'
            '|  _ \ |_ _|| \ | | / ___||_ _||  ___|\ \ / /'
            '| |_) | | | |  \| || |  _  | | | |_    \ V / '
            '|  __/  | | | |\  || |_| | | | |  _|    | |  '
            '|_|    |___||_| \_| \____||___||_|      |_|  ')
    fi
}

banner_line() {
    local text=$1 colour=$2 inner=$((UI_W - 6)) pad s
    _vislen "$text"
    pad=$(((inner - VL) / 2))
    [ "$pad" -lt 0 ] && pad=0
    printf -v s '%*s%s%s%s' "$pad" '' "$colour" "$text" "$C_OFF"
    panel_row "$s"
}

# wipe clears the screen at the top of a screen, and only there. It moves
# the cursor home and erases what is on the screen without touching the
# scrollback, so everything drawn before is still a page up. A held screen
# is on its way to a terminal, so it is cleared as well.
wipe() {
    [ -t 1 ] || [ -n "$UI_HELD" ] || return 0
    [ "$UI_COLOR" = none ] && return 0
    printf '\033[H\033[2J'
}

banner() {
    local extra=${1:-} line
    wipe
    # The art is fifty wide. Under that it is not a word mark, it is a
    # handful of blocks in the wrong places.
    if [ "$((UI_W - 6))" -lt 50 ]; then
        blank
        printf '  %s%sPINGIFY%s  %sIran %s Kharej tunnel%s\n' \
            "$C_CYN" "$C_B" "$C_OFF" "$C_DIM" "$BX_ARR" "$C_OFF"
        blank
        return 0
    fi
    # The same frame on every screen, so it is drawn once and kept: the
    # blocks are measured glyph by glyph, which is too slow to do again for
    # every screen on a busy server. Drawn again when the window, the glyphs
    # or the colours change.
    local key="$UI_W|$UI_GLYPH|$UI_COLOR|$extra"
    if [ "$key" != "$UI_BANNER_KEY" ]; then
        UI_BANNER=$(banner_draw "$extra")
        UI_BANNER_KEY=$key
    fi
    printf '%s\n' "$UI_BANNER"
}
UI_BANNER= UI_BANNER_KEY=
banner_draw() {
    local line
    blank
    panel ""
    _banner_art
    for line in "${BA[@]}"; do
        banner_line "$line" "$C_CYN$C_B"
    done
    banner_line "by Teejay   $BX_DOT   Iran $BX_ARR Kharej tunnel" "$C_DIM"
    [ -n "${1:-}" ] && banner_line "$1" "$C_DIM"
    panel_end
}

# ---------------------------------------------------------------------------
# a screen at once
#
# A menu screen is worked out as it is printed - the core asked for its
# status, a file read, a service looked at - so on a server busy with its
# users it drew itself from the top down over a second. ui_hold sends what
# follows to a file and ui_show puts the lot on the terminal in one write:
# the last screen stays until the next one is ready. Every question shows
# what is held before it asks, so nothing is asked under a screen that has
# not appeared. Only a terminal is held; a pipe or a test sees each line as
# it is printed, as before.
# ---------------------------------------------------------------------------

UI_HELD= UI_BUF=
ui_hold() {
    [ -z "$UI_HELD" ] && [ -t 1 ] || return 0
    if [ -z "$UI_BUF" ]; then
        # Beside the state, which only root can write: a name in /tmp that
        # can be guessed is a name another user could have linked elsewhere.
        [ -d "${STATE_DIR:-}" ] || return 0
        UI_BUF=$STATE_DIR/.screen.$$
        ui_buf_sweep
    fi
    : >"$UI_BUF" 2>/dev/null || return 0
    exec 4>&1 1>"$UI_BUF"
    UI_HELD=1
}
ui_show() {
    [ -n "$UI_HELD" ] || return 0
    exec 1>&4 4>&-
    UI_HELD=
    cat "$UI_BUF"
}
ui_done() { ui_show; [ -z "$UI_BUF" ] || rm -f "$UI_BUF"; }
# The screen file of a session that was killed rather than left.
ui_buf_sweep() {
    local f p
    for f in "$STATE_DIR"/.screen.*; do
        [ -e "$f" ] || continue
        p=${f##*.}
        case $p in '' | *[!0-9]*) continue ;; esac
        [ "$p" = "$$" ] || kill -0 "$p" 2>/dev/null || rm -f "$f"
    done
}
screen_top() { banner; }

# ---------------------------------------------------------------------------
# the wizard
#
# The steps run down one page. Nothing is cleared between them, so the
# answers already given stay on screen above the question being asked - which
# is what you want when you are copying the same numbers onto a second
# server. Half a wizard is not a tunnel, so q at any question leaves.
# ---------------------------------------------------------------------------

WIZ_STEP=0
WIZ_ACTIVE=0
WIZ_QUIT=0
wiz_reset() { WIZ_STEP=0; WIZ_ACTIVE=1; WIZ_QUIT=0; }
wiz_end()   { WIZ_ACTIVE=0; WIZ_QUIT=0; }

# wiz <title> [subtitle] - open a step.
wiz() {
    WIZ_STEP=$((WIZ_STEP + 1))
    local t="$WIZ_STEP $BX_DOT $1 "
    _vislen " $t"
    _rep "$BX_H" $((UI_W - VL - 5))
    printf '\n  %s%s%s%s%s%s%s\n\n' \
        "$C_GRY" "$BX_H$BX_H " "$C_OFF$C_CYN$C_B" "$t" "$C_OFF$C_GRY" "$RP" "$C_OFF"
    [ -n "${2:-}" ] && { dim "$2"; blank; }
    return 0
}

# choice <key> <name> <hint> - one option, name and reason on the same line.
# CHOICE_DEF marks the one enter picks, on the line itself.
CHOICE_DEF=""
choice() {
    local mark="   " hint=${3:-} name
    if [ "$1" = "$CHOICE_DEF" ]; then
        mark="${C_GRN}${BX_ARR}${C_OFF}  "
        hint="${hint}${hint:+  }${C_GRN}(default)${C_OFF}"
    fi
    _pad "${C_B}$2${C_OFF}" 14
    name=$PD
    _trunc "$hint" $((UI_TERM - 25))
    printf '  %s%s%2s%s  %s  %s%s%s\n' \
        "$mark" "$C_CYN$C_B" "$1" "$C_OFF" "$name" "$C_DIM" "$TR" "$C_OFF"
}

pause() {
    ui_show
    printf '\n'
    read -rsp "  ${C_DIM}press enter${C_OFF}" _ || true
    printf '\n'
}

# ---------------------------------------------------------------------------
# asking
#
# ask VAR "prompt" ["default"] [validator]
#
# A validator prints why it refused and returns non-zero; the reason is shown
# under the prompt and the question is asked again. q leaves, and once the
# wizard is leaving every later question returns without asking, so it
# unwinds instead of finishing. End of input is not an answer to wait for: a
# piped script that runs out stops here rather than asking for ever.
#
# The locals are prefixed because bash scopes locals dynamically: a caller
# that names its own variable `def` and passed it here would have had it
# overwritten by this function's own.
# ---------------------------------------------------------------------------

ask() {
    local _pk_var=$1 _pk_prompt=$2 _pk_def=${3:-} _pk_check=${4:-} _pk_in _pk_err _pk_rc
    [ "${WIZ_QUIT:-0}" = 1 ] && return 1
    ui_show
    while :; do
        _pk_rc=0
        if [ -n "$_pk_def" ]; then
            read -rp "  ${C_CYN}${BX_ARR}${C_OFF} ${_pk_prompt} ${C_DIM}[${_pk_def}]${C_OFF}${C_B}:${C_OFF} " _pk_in || _pk_rc=1
        else
            read -rp "  ${C_CYN}${BX_ARR}${C_OFF} ${_pk_prompt}${C_B}:${C_OFF} " _pk_in || _pk_rc=1
        fi
        # Standard input has ended. No answer is coming, and a default taken
        # here would answer every remaining question by itself.
        if [ "$_pk_rc" = 1 ]; then
            [ "${WIZ_ACTIVE:-0}" = 1 ] && WIZ_QUIT=1
            return 1
        fi
        [ -z "$_pk_in" ] && _pk_in=$_pk_def
        case $_pk_in in
        q | Q | quit) WIZ_QUIT=1; return 1 ;;
        esac
        if [ -z "$_pk_check" ]; then
            printf -v "$_pk_var" '%s' "$_pk_in"
            return 0
        fi
        if _pk_err=$("$_pk_check" "$_pk_in" 2>&1); then
            printf -v "$_pk_var" '%s' "$_pk_in"
            return 0
        fi
        fail "${_pk_err:-not a valid answer}"
    done
}

# pick VAR "prompt" DEFAULT N - one of the numbers 1..N, and nothing else.
# An empty default means the question has no default: which server this is,
# what transport to speak - an empty enter that quietly means "the first one"
# is how somebody ends up with a tunnel they did not choose.
pick() {
    # Its own name for the answer: ask declares a local of its own with the
    # usual one, and bash scopes locals dynamically, so an answer written
    # into that name would land in ask's copy and this loop would never end.
    local _pk_var=$1 _pk_prompt=$2 _pk_def=${3:-} _pk_n=$4 _pk_ans
    while :; do
        ask _pk_ans "$_pk_prompt" "$_pk_def" v_raw || return 1
        case $_pk_ans in
        '') fail "this one has no default - choose 1 to $_pk_n"; continue ;;
        *[!0-9]*) ;;
        *) if [ "$_pk_ans" -ge 1 ] && [ "$_pk_ans" -le "$_pk_n" ]; then
               printf -v "$_pk_var" '%s' "$_pk_ans"
               return 0
           fi ;;
        esac
        fail "not one of the options - choose 1 to $_pk_n"
    done
}

# confirm "question" [y|n] - the default is no unless said otherwise.
confirm() {
    local _pk_prompt=$1 _pk_def=${2:-n} _pk_in _pk_hint='[y/N]'
    [ "$_pk_def" = y ] && _pk_hint='[Y/n]'
    [ "${WIZ_QUIT:-0}" = 1 ] && return 1
    ui_show
    while :; do
        if ! read -rp "  ${C_YEL}?${C_OFF} $_pk_prompt ${C_DIM}${_pk_hint}${C_OFF}${C_B}:${C_OFF} " _pk_in; then
            [ "${WIZ_ACTIVE:-0}" = 1 ] && WIZ_QUIT=1
            return 1
        fi
        [ -z "$_pk_in" ] && _pk_in=$_pk_def
        case $_pk_in in
        y | Y | yes | YES) return 0 ;;
        n | N | no | NO) return 1 ;;
        # q leaves a wizard. Outside one it is only a no: a flag set here
        # would answer every later question on every screen by itself.
        q | Q) [ "${WIZ_ACTIVE:-0}" = 1 ] && WIZ_QUIT=1; return 1 ;;
        esac
    done
}

# confirm_yes is confirm with the answer already leaning the right way: by the
# time it is asked, everything has been reviewed and the expected reply is yes.
confirm_yes() { confirm "$1" y; }

# menu_key VAR - the number a screen is waiting for. A line, not a keystroke,
# so a screen with more than ten things on it can be answered, and so the
# answer arrives the same way when there is no terminal at all.
# menu_key reads one answer on a screen of numbered items. It answers 0 for
# q as well, so that leaving a screen is the same key everywhere: q used to
# work on the front page and nowhere else, and on one screen it fell out of
# the menu entirely.
menu_key() {
    local _pk_var=$1 _pk_in
    ui_show
    read -rp "  ${C_CYN}${BX_ARR}${C_OFF} select${C_B}:${C_OFF} " _pk_in || return 1
    _pk_in=${_pk_in#"${_pk_in%%[![:space:]]*}"}
    _pk_in=${_pk_in%"${_pk_in##*[![:space:]]}"}
    case $_pk_in in q | Q | b | B) _pk_in=0 ;; esac
    printf -v "$_pk_var" '%s' "$_pk_in"
}

# ---------------------------------------------------------------------------
# validators
# ---------------------------------------------------------------------------

v_any() { [ -n "$1" ] || { echo "say something"; return 1; }; }
v_raw() { return 0; }

v_host() {
    local h=$1 o
    [ -n "$h" ] || { echo "an address is required"; return 1; }
    if [[ $h =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        for o in ${h//./ }; do
            [ "$o" -le 255 ] || { echo "$h: $o is not part of an address"; return 1; }
        done
        return 0
    fi
    case $h in
    *:*) echo "$h is an IPv6 address; the tunnel runs over IPv4 - use the server's IPv4 address"; return 1 ;;
    *[!a-zA-Z0-9.-]* | .* | *. | *..*) echo "$h is not an IPv4 address or a domain"; return 1 ;;
    *[a-zA-Z]*.*) return 0 ;;
    esac
    echo "$h is not an IPv4 address or a domain"
    return 1
}

# v_ip4 is v_host for the kernel-carried transport, whose device takes an
# address and not a name.
v_ip4() {
    v_host "$1" || return 1
    [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "the kernel link needs the IPv4 address itself, not a name"; return 1; }
    return 0
}

v_port() {
    case $1 in '' | *[!0-9]*) echo "a port is a number"; return 1 ;; esac
    { [ "$1" -ge 1 ] && [ "$1" -le 65535 ]; } || { echo "a port is between 1 and 65535"; return 1; }
}

v_octet() {
    case $1 in '' | *[!0-9]*) echo "a number from 1 to 254"; return 1 ;; esac
    { [ "$1" -ge 1 ] && [ "$1" -le 254 ]; } || { echo "between 1 and 254"; return 1; }
}

v_mtu() {
    case $1 in '' | *[!0-9]*) echo "an mtu is a number"; return 1 ;; esac
    { [ "$1" -ge 576 ] && [ "$1" -le 9000 ]; } ||
        { echo "the core takes 576 to 9000; 1320 is what works on most paths"; return 1; }
}

# The AmneziaWG link this core runs inside. One number, in one place: the
# link MTU written into the file, and the tun MTU derived from it. On the awg
# device every packet is 20 of IP, 8 of UDP and 12 of framer over what the
# tun device hands up - and with parity on, which can be switched on later
# without anybody revisiting the MTU, 4 more in front of every packet and 2
# more in the parity packet, which carries each payload's length. So the tun
# MTU is the link less 46, always. It was a literal 1280 beside a literal
# 1320, right by 4 bytes of luck and unchecked against anything; then 44,
# which left every parity packet 2 bytes over the link.
AWG_LINK_MTU=1320
awg_tun_mtu() { echo $((AWG_LINK_MTU - 46)); }
# The wizard writes the cautious number, which holds with parity on or off.
# What is accepted is the real ceiling with parity off, because every
# AmneziaWG tunnel from before 1.1.0 runs at exactly that; turning parity on
# for one of those is refused by the core with the number to set instead.
v_mtu_awg() {
    v_mtu "$1" || return 1
    [ "$1" -le "$((AWG_LINK_MTU - 40))" ] ||
        { echo "inside AmneziaWG the link is $AWG_LINK_MTU, so this is at most $((AWG_LINK_MTU - 40)), or $(awg_tun_mtu) with parity"; return 1; }
}

# tun_overhead TRANSPORT [FEC] - what a private link puts around each packet
# on the wire, over the packet itself: the outer IP header and whatever the
# transport adds. The link's MTU plus this has to fit the interface it rides,
# or every full packet is too big for it - which is what a GRE FOU link at
# 1400 did on an Iranian server whose interface is 1400: 36 bytes over on
# every one (docs/measured.md section 42). With parity on (FEC above 0) a
# packet carries 4 more in front, and a parity packet 2 more again, for the
# length it carries (carrier/fec.go): 6 in all, on the transports that have
# parity at all.
tun_overhead() {
    local o
    case $1 in
    grefou) o=36 ;; # IP 20, UDP 8, GRE 4, key 4
    gre) o=32 ;;    # IP 20, and a GRE header of 12 that holds the key and
    #                 the sequence itself: this carrier has no framer
    rawtcp) o=52 ;; # IP 20, TCP 20, frame 12
    awg) o=100 ;;   # tun to awg link 40, awg link to wire 60
    *) o=40 ;;      # udp, icmp: IP 20, UDP or ICMP 8, frame 12
    esac
    case $1 in
    udp | icmp | rawtcp | awg)
        case ${2:-0} in '' | 0 | *[!0-9]*) ;; *) o=$((o + 6)) ;; esac ;;
    esac
    echo "$o"
}

# tun_mtu_fit TRANSPORT PEER WANT [FEC] - WANT, or less if the interface
# packets to PEER leave by cannot carry WANT plus the transport's overhead.
# Where the interface cannot be found, WANT as it is.
tun_mtu_fit() {
    local dev m
    dev=$(grefou_underlay "$2")
    m=$(cat "${SYSFS_NET:-/sys/class/net}/${dev:-none}/mtu" 2>/dev/null)
    case $m in '' | *[!0-9]*) echo "$3"; return 0 ;; esac
    m=$((m - $(tun_overhead "$1" "${4:-0}")))
    if [ "$m" -lt "$3" ]; then echo "$m"; else echo "$3"; fi
}

v_token() {
    [ "${#1}" -ge 8 ] || { echo "the core wants at least eight characters"; return 1; }
}

v_name() {
    case $1 in '' | *[!a-zA-Z0-9_-]*) echo "letters, digits, dash and underscore"; return 1 ;; esac
    [ "${#1}" -le 24 ] || { echo "keep it under twenty-five characters"; return 1; }
}

v_number() {
    case $1 in '' | *[!0-9]*) echo "a number"; return 1 ;; esac
}

# ---------------------------------------------------------------------------
# waiting
# ---------------------------------------------------------------------------

# spin "message" command... - runs the command and shows that something is
# happening, so a download or a build never looks frozen. Nothing is drawn
# when nobody is watching.
spin() {
    local msg=$1
    shift
    ui_show
    if [ ! -t 2 ] || [ "$UI_COLOR" = none ]; then "$@"; return $?; fi
    "$@" &
    local pid=$! i=0 frames='|/-\'
    while kill -0 "$pid" 2>/dev/null; do
        printf '\r  %s%s%s %s ' "$C_CYN" "${frames:i++%4:1}" "$C_OFF" "$msg" >&2
        sleep 0.1
    done
    wait "$pid"
    local rc=$?
    printf '\r%*s\r' $((${#msg} + 8)) '' >&2
    return $rc
}

ui_detect
trap 'ui_detect' WINCH
